### ISSUE TITLE
Missing exports from ember/component

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/ember-cli-typescript#1031]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [x] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41039

The above just needs finished by someone who has a few spare minutes / is familiar with DT

##### Reproduction Case
I discovered these missing types when implementing a custom component via the public component manager apis

**Link: ** https://github.com/NullVoxPopuli/ember-lifecycle-component/blob/master/addon/-private/lifecycle/index.ts

If you delete my custom types for ember component, you'll see the errors

### Now about that bug. What did you expect to see?
The public component apis to be typeh

### What happened instead?
The types are missing

**Comment by chriskrycho** [comment]
Thanks for reporting – for our ease of iterating on this, would you mind updating the issue description with the actual missing APIs and links to the docs for them? That'll help one of us knock this out. Thanks!

**Comment by chriskrycho** [comment]
We shipped types from Ember itself, so this is no longer an issue. 🎉
