### ISSUE TITLE
[@types/ember__routing] Incorrect types for TransitionTo

### ISSUE THREAD

**Issue by Alonski** [typed-ember/ember-cli-typescript#1036]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support

ember g route application
```

##### Reproduction Case

In the application route inside the afterModel hook write:
`this.transitionTo( { queryParams: { some: "thing" } } );`

### Now about that bug. What did you expect to see?

No type errors

### What happened instead?

Typescript seems to think that passing in only queryParams isn't valid.
According to this it is:
https://guides.emberjs.com/release/routing/query-params/#toc_transitionto

### This is declared in:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__routing/router-service.d.ts#L153

**Comment by chriskrycho** [comment]
The declaration in question is actually [this one in `route.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__routing/route.d.ts#L190:L204), *not* the `RouterService` types. The API docs for the latter actually don't specify the QPs-only form, but I would *assume* it's intended to support it? cc. @chadhietala @rwjblue – I'm happy to update the docs for `RouterService` as well if need be, so we can fix this in both places if we should.

@Alonski do you know what the state of `transitionToRoute` on `Controller` is?

**Comment by Alonski** [comment]
@chriskrycho I tried all transitionTo functions I know and I'm pretty sure all have the same issue.

**Comment by rwjblue** [comment]
@chriskrycho yes, it should support QP only in both the router service and the route.

**Comment by chriskrycho** [comment]
Very good. I will update docs and types this week!

**Comment by chriskrycho** [comment]
- [docs (and internal types) PR](https://github.com/emberjs/ember.js/pull/18759)
- [DefinitelyTyped PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42544)

**Comment by pieter-v** [comment]
The  #42544 introduced a new problem:
```
transitionTo(name: string, ...modelsOrOptions: object[]): Transition;
```
The parameter `modelsOrOptions` can be a model, but also an identifier. If the identifier  is a`string`, then typescript complains, as a primitive type is not assignable to `object`.

**Comment by chriskrycho** [comment]
Huh. What is it an identifier *for* in that case? (Happy to peovide the further fixes here, though also: ugh.)

**Comment by pieter-v** [comment]
It is the id of a model, and the route will load the model from the server.

**Comment by chriskrycho** [comment]
Got it, it's this bit from the docs, which I just missed entirely while working on this:

> If a literal is passed (such as a number or a string), it will be treated as an identifier instead. In this case, the `model` hook of the route will be triggered:
> 
> ```js
> this.transitionTo('blogPost', 1);
> ```

Happily, this is easy to add, and via use of overloads we should be able to get safety for this variant (still can't get it for the passing-a-model-object variant, but that just is what it is.):

```ts
this.transitionTo('blogPost', 1, { queryParams: { includeComments: true } });
```

Will try to get this PR open sometime today.

**Comment by chriskrycho** [comment]
Opened at DefinitelyTyped/DefinitelyTyped#42589 – *hopefully* that's the last one of these fixes for a bit. 😂

**Comment by chriskrycho** [comment]
Fixed! Closing this as resolved. If someone has further problems, please open a new issue!
