### ISSUE TITLE
`PromiseObject<T>` should extend `PromiseProxyMixin<T | null>`, not `PromiseProxyMixin<T & ObjectProxy>`

### ISSUE THREAD

**Issue by oliverlangan** [typed-ember/ember-cli-typescript#1094]
Based on a Discord conversation with @chriskrycho on 2020.02.17.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d129b9b777901659b1559f9355f9548496e72a2b/types/ember-data/index.d.ts#L919:L921

### Which package(s) does this problem pertain to?
  - [x] @types/ember-data

### What are instructions we can follow to reproduce the issue?
given:
```
class Comment extends Model {
  @belongsTo('post')
  post!; DS.PromiseObject<Post>;
}
```

### Now about that bug. What did you expect to see?
Resolving that promise should result in an object of type <Post | null>.

### What happened instead?
The type hints in vscode indicate instead that it would `Post & ObjectProxy<object>`.

It would be _nice_ if the expected nullability (from the API) could be specified, so that the returned value was either `Post` or `Post | null`; but in either case the `ObjectProxy<object>` should not be part of the returned types.

**Comment by chriskrycho** [comment]
A couple observations here—

1. I don’t *think* the resolved type should be `T & ObjectProxy<object>`—at a minimum it probably needs to be `T & ObjectProxy<T>`, but I *think* it shouldn't be `ObjectProxy` at all if it has been `await`-ed or within a `then` callback.

2. We need to support opting *out* of a `null` (or `undefined`?) resolved type, while letting that be in the default for it. My thought process here is: we want to capture the *real* default behavior for Ember Data, but we also want to let users say “No, my API will never be `null` in this response.”

A related but important question, as I haven’t poked at this particular behavior of Ember Data in a while: if you `await someModel.someAysncRelationship` and the lookup *fails*—e.g. there’s a network timeout—what actually happens? Does it throw an exception, or does it resolve as `undefined` or `null`?

**Comment by oliverlangan** [comment]
If an `async` call to the API fails, it throws an exception into the `catch` block. (Or if resolved with `then`, into the `catch` handler.)

**Comment by chriskrycho** [comment]
Thanks. That matches what I expected!

**Comment by chriskrycho** [comment]
I think this got resolved in Ember Data’s types on DT? Feel free to reopen if not/still relevant.
