### ISSUE TITLE
build errors with latest ember (3.16.0) and ember-cli-typescript with new project

### ISSUE THREAD

**Issue by shofmannka** [typed-ember/ember-cli-typescript#1101]
### Please paste the output of `ember -v` here
  ember-cli: 3.16.0
  node: 12.13.0
  os: win32 x64 (windows 10)

### Please paste the output of `tsc -v` here
 tsc not found

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here
  ember-cli-typescript@3.1.3
  ember-cli-typescript-blueprints@3.0.0

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

  
tsconfig.json:
{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "experimentalDecorators": true,
    "paths": {
      "ts-test/tests/*": [
        "tests/*"
      ],
      "ts-test/*": [
        "app/*"
      ],
      "*": [
        "types/*"
      ]
    }
  },
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*"
  ]
}
  
</pre></details>

<details><summary><b>My tslint.json or eslint.json</b></summary><pre>
tslint.json:
does not exist
  

</pre></details>

### What are instructions we can follow to reproduce the issue?

>> Your Instructions Go Here <<
windows cmd
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember s

##### Reproduction Case
--> result
![image](https://user-images.githubusercontent.com/28725436/75175826-56d57600-5733-11ea-8036-44d6e3eeb6cc.png)

**Comment by jeffsawatzky** [comment]
Same issue here, but with node 13.8.0
```
ember-cli: 3.16.0
node: 13.8.0
os: darwin x64
```

package.json
```
{
  "name": "sample",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for sample goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build --environment=production",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember/optional-features": "^1.3.0",
    "@glimmer/component": "^1.0.0",
    "@glimmer/tracking": "^1.0.0",
    "@types/ember": "^3.1.1",
    "@types/ember-data": "^3.1.9",
    "@types/ember-qunit": "^3.4.7",
    "@types/ember__test-helpers": "^0.7.9",
    "@types/qunit": "^2.9.0",
    "@types/rsvp": "^4.0.3",
    "babel-eslint": "^10.0.3",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.5.3",
    "ember-cli": "~3.16.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.17.2",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^4.2.2",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.3",
    "ember-cli-typescript": "^3.1.3",
    "ember-cli-typescript-blueprints": "^3.0.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-data": "~3.16.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^7.0.0",
    "ember-load-initializers": "^2.1.1",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.6.0",
    "ember-resolver": "^7.0.0",
    "ember-source": "~3.16.0",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "^7.7.2",
    "eslint-plugin-node": "^11.0.0",
    "loader.js": "^4.7.0",
    "qunit-dom": "^1.0.0",
    "typescript": "^3.8.2"
  },
  "engines": {
    "node": "10.* || >= 12"
  },
  "ember": {
    "edition": "octane"
  }
}
```

**Comment by mydea** [comment]
I think this is actually due to typescript. I get the same thing updating from 3.7.5 to 3.8.2, which is in-range if using e.g. `typescript@^3.7.0`. Fixing it to e.g. `typescript@~3.7.5` works for me...!

**Comment by shofmannka** [comment]
@mydea i have tried to use typescript@3.7.5 but i get the same error.

**Comment by mydea** [comment]
Have you fixed the dependency like this:

```
"typescript": "~3.7.5"
```

Note the tilde instead of the caret? It works for me with 3.7.5 and ember 3.16.3.

**Comment by shofmannka** [comment]
@mydea ok, with ~ instead of ^ it works. Thanks.

**Comment by eelke** [comment]
Had the same issue, and using @mydea's suggestion worked for me.

**Comment by chriskrycho** [comment]
I don't believe this is an ongoing issue. Also, we now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tsc` directly on their projects. Accordingly, although this *should not* be an issue, even if it is we will not be addressing it, as we are moving this package into maintenance mode. Thanks!
