### ISSUE TITLE
Can `tmpl` in `global.d.ts` be renamed to `global`?

### ISSUE THREAD

**Issue by Bouke** [typed-ember/ember-cli-typescript#1104]
The blueprint defines a file named `global.d.ts` with the following contents:

```ts
// Types for compiled templates
declare module 'cb-ember/templates/*' {
  import { TemplateFactory } from 'htmlbars-inline-precompile';
  const tmpl: TemplateFactory;
  export default tmpl;
}
```

https://github.com/typed-ember/ember-cli-typescript/blob/2bc8d46a00323627e2c3fa368060b57b5cf31e4a/ts/blueprints/ember-cli-typescript/index.js#L23

Our linter (SonarQube) raises an error about the `tmpl` export:

> Default export names and file names should match
>
> By convention, a file that exports only one class, function, or constant should be named for that class, function or constant. Anything else may confuse maintainers.
>
> Source: https://sonarcloud.io/organizations/microsoft/rules?open=typescript%3AS3317&rule_key=typescript%3AS3317

I guess we could rename `tmpl` to `global`, but what is your take on this? Is this a change worthwhile to upstream to this project?

**Comment by chriskrycho** [comment]
SonarQube is just *wrong* in this case; it's mis-analyzing the source code here and failing to understand (a) what `global.d.ts` is and (b) what the module declaration is actually doing. This could at most be renamed to `template`, but it *certainly* should not be named `global`. If possible, you should file a bug on SonarQube, presumably with a link to these two pieces of the TS docs:

- [`global.d.ts` example](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html)
- [wildcard module declarations](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations)

Hope that's helpful!
