### ISSUE TITLE
Install @types/ember-data__* by default

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/ember-cli-typescript#1109]
This is a reminder issue, for https://discordapp.com/channels/480462759797063690/484421406659182603/683369672594292750

at the moment, `@ember-data/` types are not installed

**Comment by makepanic** [comment]
Is there a plan on where to do this?
Should DefinitelyTyped ship them?

I think I might have some time to port the existing types to `@ember-data/*` as it's kinda blocking the `ember/use-ember-data-rfc-395-imports` linting rule.

**Comment by chriskrycho** [comment]
@makepanic these exist on Definitely Typed *now* (and [have since the end of January](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42017)) – this issue is tracking *installing them by default*.

**Comment by chriskrycho** [comment]
To elaborate the above – if anyone is interested in doing this, all you have to do is update the existing implementation [here](https://github.com/typed-ember/ember-cli-typescript/blob/2bc8d46a00323627e2c3fa368060b57b5cf31e4a/ts/blueprints/ember-cli-typescript/index.js#L153:L155) and [the tests](https://github.com/typed-ember/ember-cli-typescript/blob/e0e531fba24952d955422fa9c6161c51b38dd372/ts/tests/blueprints/ember-cli-typescript-test.ts).

The key for updating the existing implementation is that we should use version checker to make sure we only do it if users have installed a version of Ember Data which supports the exports. @runspired @rwjblue I believe you looked at making the Babel polyfill for the modules work back a ways – did that happen, and if so, how far back?

**Comment by Bouke** [comment]
If people are wondering what to install manually, I think this is the list:
- @types/ember-data__adapter
- @types/ember-data__model
- @types/ember-data__serializer
- @types/ember-data__store

**Comment by karbica** [comment]
@Bouke Thanks for that list. Is there an official list of other packages to install manually after installing `ember-cli-typescript`?

I'm getting errors import from modules that I didn't get before moving to TypeScript. One example is from `@ember-data/model`.

**Comment by MrChocolatine** [comment]
I am reviving this issue, should we add these new types to the blueprint?

https://github.com/typed-ember/ember-cli-typescript/blob/7098f983f666039a0fff369ea47df6f96d248081/ts/blueprints/ember-cli-typescript/index.js#L146-L169

**Comment by jamescdavis** [comment]
Fixed in #1411
