### ISSUE TITLE
Enumerable.filterBy has a wrong return type

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#1120]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__array

`Enumerable.filterBy` (and possibly all other methods that are marked to return `NativeArray<T>`) doesn't actually return a `NativeArray` but rather a native JavaScript array. It's as simple as typing:

```typescript
import { A } from '@ember/array';

const result = A().filterBy('foobar').mapBy('foobar');
```

This type-checks fine but at runtime blows up because `filterBy` doesn't return something that has a `mapBy` method.

**Comment by chriskrycho** [comment]
Thank you! I'll see if I can land a fix this week!

**Comment by chriskrycho** [comment]
Resolved by publishing types from Ember itself. (It's also possible this got fixed incidentally on DT at some point!)
