### ISSUE TITLE
Missing type for recognize method in RouterService

### ISSUE THREAD

**Issue by josemarluedke** [typed-ember/ember-cli-typescript#1146]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?

```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
```

##### Reproduction Case

```ts
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import RouterService from '@ember/routing/router-service';

interface DocfyLinkArgs {
  to: string;
}

export default class DocfyLink extends Component<DocfyLinkArgs> {
  @service router!: RouterService; 

  get routeName(): string {
    return this.router.recognize(this.args.to);
   // GET ERROR HERE.
  }
}
```

### Now about that bug. What did you expect to see?
No errors, the type info should be there. 

### What happened instead?

Property 'recognize' does not exist on type 'RouterService'.

**Comment by chriskrycho** [comment]
Thanks for reporting! If you ping in Discord I’m happy to help you through fixing it on DefinitelyTyped!

**Comment by jamescdavis** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49296
