### ISSUE TITLE
Documentation: Clarify `loose: true`

### ISSUE THREAD

**Issue by dustinsoftware** [typed-ember/ember-cli-typescript#1203]
When updating to e-c-ts 3.4, we discovered a surprising change to how the class properties plugin behaves.

`loose: true` was being defined previously by e-c-ts, but now that we're relying on `ember-cli-babel` to add it for us, `loose: false` became the default. 

Defining `loose: true` in `ember-cli-build` restores the previous behavior.

```js
    babel: {
      sourceMaps: IS_PROD,
      plugins: [
        '@babel/plugin-proposal-optional-chaining',
        '@babel/plugin-proposal-nullish-coalescing-operator',
        'ember-auto-import/babel-plugin',
      ],
      loose: true
    },
```

Should the previous behavior of `loose: true` be documented somewhere in the changelog or upgrade notes?

e-c-ts change: https://github.com/typed-ember/ember-cli-typescript/commit/204d7404bfd54cf3bb8ffb7d9e35a9ddef127e25#diff-287bcabd2443a8d80ebe0fb212241315L83-L90

**Comment by dfreeman** [comment]
Sorry to hear you ran into that!

Going through the history, it looks like `loose: true` was `ember-cli-babel`'s default when we made that change in May 2019. Their default swapped to `false` and became overridable [as a bugfix](https://github.com/babel/ember-cli-babel/pull/307) about six months later, and I know of one or two other groups who were tripped up by that change as well (indepentent of TypeScript).

Given that the change was over there and not in `ember-cli-typescript`, I'm not quite sure what release notes or upgrade guide it would make sense to attach this info to, but if you've got an idea for where it could be helpful, a PR to the docs would be welcome 🙂

**Comment by dustinsoftware** [comment]
I think I'll leave this issue as the "documentation" for it in case others find it... Thanks for the reply :)
