### ISSUE TITLE
Router service is missing rootURL property

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/ember-cli-typescript#1257]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```ts
import type RouterService from '@ember/routing/router-service';

// ...
@service router!: RouterService;

// ...

this.router.rootURL;
//           ^ Property 'rootURL' does not exist on type 'RouterService'.
```

https://api.emberjs.com/ember/3.9/classes/RouterService/properties/rootURL?anchor=rootURL

- typescript 3.9.7
- ec-ts 4-alpha.1
- ember-3.16
- @types/ember: 3.16.0

**Comment by NullVoxPopuli** [comment]
looks like we're also missing `recognize()`

**Comment by NullVoxPopuli** [comment]
should RouteInfo be public? 
just implementing a temporary version of this locally:

```ts
import type RouteInfo from '@ember/routing/-private/route-info';
import type RouterService from '@ember/routing/router-service';

type RouterWithMissingTypes = RouterService & {
  recognize(url: string): RouteInfo;
  rootURL: string;
};
```

**Comment by jamescdavis** [comment]
This should be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49296
