### ISSUE TITLE
RouteInfo missing metadata property

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/ember-cli-typescript#1261]
I ended up solving locally via:

```ts
import type { default as EmberRouteInfo } from '@ember/routing/-private/route-info';
import type { default as EmberRouterService } from '@ember/routing/router-service';

// RouterService is missing rootURL and recognize()
// https://github.com/typed-ember/ember-cli-typescript/issues/1257
type RouterService = EmberRouterService & {
  recognize(url: string): RouteInfo;
  rootURL: string;
};

type RouteInfo = EmberRouteInfo & {
  metadata?: TODO; // would need a RouteRegistry lookup?
};
```
(relates to https://github.com/typed-ember/ember-cli-typescript/issues/1257)

### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
- create new ts ember app
- copy above type declaration into global.d.ts or index.d.ts
- access `this.router.recognize('some url').metadata`
- receive error message: "metadata does not exist on type RouteInfo"

looks like documentation is out of date as well,
recognize returns RouteInfo: https://api.emberjs.com/ember/3.20/classes/RouterService/methods/recognize?anchor=recognize
bout RouteInfo isn't said to have metadata: https://api.emberjs.com/ember/release/classes/RouteInfo

but it certainly does, as is public API, cause of the RouteInfoMetadata RFC (from Ember 3.10?)
https://emberjs.github.io/rfcs/0398-RouteInfo-Metadata.html#routeinfometadata

**Comment by jamescdavis** [comment]
I opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49296. It doesn't add `metadata` to `RouteInfo`, but rather adds [RouteInfoWithAttributes](https://api.emberjs.com/ember/release/classes/RouteInfoWithAttributes). As you pointed out, the documentation says that `recognize()` returns `RouteInfo` and I have added it as such. There is also [recognizeAndLoad](https://api.emberjs.com/ember/3.6/classes/RouterService/methods/recognize?anchor=recognizeAndLoad), which *does* return `RouteInfoWithAttributes`.

**Comment by jamescdavis** [comment]
After reviewing more carefully, I believe this is a deficiency of the API docs. I have opened https://github.com/emberjs/ember.js/pull/19248 to add documentation of `RouteInfo.metadata`. Once that goes in, we can amend the types to add `metadata` to `RouteInfo`.

**Comment by jamescdavis** [comment]
Resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49383
