### ISSUE TITLE
error in ember-data type definition

### ISSUE THREAD

**Issue by championswimmer** [typed-ember/ember-cli-typescript#128]
`node_modules/@types/ember-data/index.d.ts(920,56): error TS2344: Type 'any' does not satisfy the constraint 'never'.`

**Comment by dwickern** [comment]
It's probably this one: https://github.com/typed-ember/ember-cli-typescript#fixing-the-ember-data-error-ts2344-problem

It should be fixed now by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23652. Try updating your `@types/ember-test-helpers` and you can remove `@types/ember-data` if you're not using it. Let me know and I'll reopen.

**Comment by championswimmer** [comment]
Actually, if we **want** to use `@types/ember-data` 
then our `types/ember-data.d.ts` to override doesn't work 

(Not sure why is it happening, if we declare module `ember-data` and add the keys, it should merge, but it isn't

So yes, removing `ember-data` works, but what if we want to keep it ?

**Comment by championswimmer** [comment]
@dwickern @dfreeman @chriskrycho 

FYI
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23652 got reverted.

seem my comment on the thread. it actually got reverted for apparently a wrong reason (travis has **not** failed)

**Comment by chriskrycho** [comment]
Related: DefinitelyTyped/DefinitelyTyped#43206
