### ISSUE TITLE
how to get coverage reports 

### ISSUE THREAD

**Issue by championswimmer** [typed-ember/ember-cli-typescript#129]
i was able to create an app and an addon using this,
my only concern is I am not able to get coverage reports to work with codecov/coveralls

Coverage for .ts files will need source maps. 

Any plans on how to support this ?

**Comment by chriskrycho** [comment]
We *are* generating source maps, but they're currently not being ingested by Babel correctly. There is something in the Broccoli/Babel pipeline that's causing this – we're not sure yet what it is.

If you feel like poking at it and seeing, we'd *love* the help. (It's mostly just @dwickern, @dfreeman, and me doing this in the niches we can carve out from our day jobs!)

**Comment by championswimmer** [comment]
Cool! Thanks for the insight. I will try to take a look into it, and maybe I can chip back in with a PR :)

**Comment by chriskrycho** [comment]
👍 Thanks for the various comments and issues – they're helpful and appreciated!

**Comment by championswimmer** [comment]
@chriskrycho 
can you give me a high level overview of what steps take place when `ember serve` or `ember test` runs ? 

Somewhere sourceMap = false is getting set, which is not passing the sourcemaps to Babel.

**Comment by chriskrycho** [comment]
@championswimmer interesting. To answer your question directly, the flow is all managed [in this module](https://github.com/typed-ember/ember-cli-typescript/blob/master/lib/incremental-typescript-compiler.js); trees are set up [here](https://github.com/typed-ember/ember-cli-typescript/blob/master/lib/incremental-typescript-compiler.js#L60-L81).

Build configuration options are set in the normal `tsconfig.json` file, and the default generated `tsconfig.json` [has `"sourceMap": true`](https://github.com/typed-ember/ember-cli-typescript/blob/743c01ab7b84764938795f69fe11f1ac015b9090/blueprints/ember-cli-typescript/files/tsconfig.json#L10).

Where and how did you identify that the source-maps were being turned *off*? (No argument implied in the question; more like befuddlement given the above!)

**Comment by chriskrycho** [comment]
A possible point of experimentation: try using various combinations of `--sourceMap`, `--inlineSourceMap`, `--inlineSources`, and *possibly most importantly* `--sourceRoot`.

@dfreeman I'm wondering if the source maps aren't getting dropped because of the source root issue. Quoting the TS compiler options docs:

> Specifies the location where debugger should locate TypeScript files instead of source locations. Use this flag if the sources will be located at run-time in a different location than that at design-time. The location specified will be embedded in the sourceMap to direct the debugger where the source files will be located.

🤔

**Comment by dfreeman** [comment]
We actually _get_ sourcemaps from `ts:precompile`, and a quick log in the app I was using to test Mirage stuff seems to indicate we're generating them during the normal build process as well:

![image](https://user-images.githubusercontent.com/108688/36433489-a23627ee-162a-11e8-8032-6c982fa574f2.png)

In general with Broccoli, though, there's a preference toward doing inline sourcemaps, as it means the build pipeline doesn't need to juggle pairs of files moving around as a single unit, so we could give that a try.

**Comment by dfreeman** [comment]
It's also worth noting that unless you've specifically overridden this, ember-cli-babel _doesn't_ consumer or produce sourcemaps—the process is just too slow for normal development.

**Comment by chriskrycho** [comment]
Yeah, you need the ember-cli-babel config set up for it, but even with that I've not seen it work.

As your results show: I *definitely* know we generate them.

**Comment by championswimmer** [comment]
I have set 

```
options: {
  'ember-cli-babel': { sourceMaps: 'both'},
  'babel': {sourceMaps: 'both'}
}
```
in my index.js

That makes me get the .js files' coverage
(Without those configs, I do not get coverage of even my .js files)

But even despite those confings, .ts files still have no coverage.

**Comment by championswimmer** [comment]
Also note, when walking back the tmp output directory, the code as it is right now, only copies back the .js and .d.ts files back to the module. The .map files **are not** being copied back into the current directory.

**Comment by chriskrycho** [comment]
_That's_ probably the problem. We're just dropping them in the final step in the pipeline. Seems like that _should_ get solved by inlining them. Can you try that?

**Comment by championswimmer** [comment]
Okay made some progress here

We need to set the options on `ember-cli-build.js` not `index.js`

```javascript
let app = new EmberAddon(defaults, {
    // Add options here
    'babel': {
      sourceMaps: 'inline'
    },
    'ember-cli-babel': {
      sourceMaps: 'inline'
    }
  });
```

And set these on my `tsconfig.json`

```javascript
    "inlineSourceMap": true,
    "sourceRoot": ".",
```

This is inlining the sourceMaps, but broccoli is unable to concat

```
ENOENT: no such file or directory, open '/Users/championswimmer/Development/Personal/EmberJS/ember-promise-utils/tmp/source_map_concat-input_base_path-XRtk7tR4.tmp/addon-tree-output/ember-promise-utils/mixins/addon/mixins/promise-resolver.ts'
```

Because it is trying to find the .ts file in `addon-tree-output`.

**Comment by championswimmer** [comment]
Not setting `sourceRoot` gives this error

```
ENOENT: no such file or directory, open '/Users/championswimmer/Users/championswimmer/Development/Personal/EmberJS/ember-promise-utils/addon/mixins/promise-resolver.ts'
```
This is confusing, because **that** file **does exist**

**Comment by dfreeman** [comment]
I'm able to get working sourcemaps in development with the following:

```diff
diff --git a/ember-cli-build.js b/ember-cli-build.js
index dc5a39e..3940e2b 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -4,7 +4,9 @@ const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

 module.exports = function(defaults) {
   let app = new EmberAddon(defaults, {
-    // Add options here
+    babel: {
+      sourceMaps: 'inline'
+    }
   });

   /*
```

```diff
index 88e43db..3a2e41d 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -7,7 +7,8 @@
     "noImplicitThis": true,
     "noEmitOnError": false,
     "noEmit": true,
-    "sourceMap": true,
+    "inlineSourceMap": true,
+    "inlineSources": true,
     "baseUrl": ".",
     "module": "es6",
     "paths": {
```

**Comment by dfreeman** [comment]
To be clear, dropping the sourcemaps for `ts:precompile` is intentional, but they're passed along normally in the regular build pipeline. I think the issue there is just that they won't necessarily get ferried through the Broccoli pipeline correctly on their own.

**Comment by championswimmer** [comment]
ok sourcemaps **are** working using @dfreeman's config

**but** coverage via `ember-cli-code-coverage` still seems not be working. I am investigating further

**Comment by dfreeman** [comment]
ember-cli-code-coverage has been almost completely rewritten since that issue was filed—it wouldn't surprise me to find out it still doesn't work, but it's probably for a totally different reason now 🙂

**Comment by championswimmer** [comment]
@dfreeman 

This will make it work I guess https://github.com/kategengler/ember-cli-code-coverage/pull/146/files 
Gonna pull that PR and try manually

**Comment by chriskrycho** [comment]
Confirm that works locally. We should update the default template for this.

**Comment by championswimmer** [comment]
```
    babel: {
      sourceMaps: 'inline'
    }
```

^^ that should be documented but not made part of the default blueprint. It slows down builds. 

The tssconfig, yep, should change the default template

**Comment by chriskrycho** [comment]
Yep, concur. If you have ten minutes to open that PR, that would be *amazing*.
