### ISSUE TITLE
`@attr` decorator cannot be used without invoking it (`@attr()` works)

### ISSUE THREAD

**Issue by chancancode** [typed-ember/ember-cli-typescript#1291]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [x] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?

See reproduction.

##### Reproduction Case

```ts
import Model, { attr } from '@ember-data/model';

export default class MyModel extends Model {
  @attr foo!: string; // TypeError: The return type of a property decorator function must be either 'void' or 'any'. Unable to resolve signature of property decorator when called as an expression.ts(1236)
  @attr() bar: string; // Ok!
}
```

### Now about that bug. What did you expect to see?

`@attr` and `@attr()` should do the same thing.

### What happened instead?

`@attr()` works but `@attr` errors.

**Comment by wagenet** [comment]
Should be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48654

**Comment by jamescdavis** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48654#issuecomment-707845847
