### ISSUE TITLE
Generated tests 'this' implicitly has type 'any' 

### ISSUE THREAD

**Issue by vlascik** [typed-ember/ember-cli-typescript#130]
Getting a flood of TS2683:
```
tests/unit/index/route-test.ts(8,17): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
tests/unit/application/route-test.ts(8,17): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
```
for every generated test.

**Comment by chriskrycho** [comment]
Do you have `@types/ember-qunit` installed?

**Comment by vlascik** [comment]
No.

**Comment by vlascik** [comment]
Right, I see the problem, generated tests use ember-qunit. After I installed the typings problem disappeared. 
Perhaps these should be installed by default then?

**Comment by chriskrycho** [comment]
Yep! See #136. Closing this in favor of that, as we're tracking a bunch of similar improvements there. Thanks for the feedback!
