### ISSUE TITLE
Including ember-data typings conflicts with alternative stores

### ISSUE THREAD

**Issue by vlascik** [typed-ember/ember-cli-typescript#131]
`ember-data` typings might conflict with alternative stores (e.g. orbit), which can provide their own store service. Perhaps there could be a check if parent application depends on ember-data before adding them?

**Comment by chriskrycho** [comment]
Good suggestion! We're currently just shipping typings to make the out-of-the-box experience for the "default" Ember install work (which includes Ember Data). A PR that checks this would be *very* welcome!

**Comment by dwickern** [comment]
If we're including `@types/ember-data` by default, we should also include catch-all type registry definitions so the code compiles out of the box

**Comment by chriskrycho** [comment]
Yeah, given the various bumps and the… *reasonably* high likelihood of [change in this area soon](https://emberconf.com/speakers.html#dan-gebhardt), I'm actually thinking we might be better off *removing* `@types/ember-data` as a default install. 🤔

**Comment by jamescdavis** [comment]
This is covered in the above referenced PR.
