### ISSUE TITLE
Invalid source maps generated

### ISSUE THREAD

**Issue by wagenet** [typed-ember/ember-cli-typescript#1322]
We're seeing situations where we get source maps with negative line numbers. I believe it only occurs in some of our TypeScript files. I hope to add more details to this ticket, but wanted to get something started for reference.

See also https://github.com/babel/ember-cli-babel/issues/364

**Comment by chriskrycho** [comment]
Thank you!

**Comment by wagenet** [comment]
Our primary version of ember-cli-typescript is 4.0.0 and ember-cli-babel is 7.22.1.

**Comment by wagenet** [comment]
Turns out that we are seeing this in some non-TS files as well. I'm not certain if that rules out ember-cli-typescript or not.

**Comment by chriskrycho** [comment]
@wagenet did you all ever get further info on this? Based on this writeup and your comments in Discord at the time, my understanding is that this is *not* ember-cli-typescript related, but would like to confirm before I close this.

**Comment by wagenet** [comment]
@chriskrycho I believe it is probably related to what is being discussed at https://github.com/babel/ember-cli-babel/issues/364. I'll close this one.

**Comment by chriskrycho** [comment]
Thanks for clarifying! I'll go watch that issue with much interest.
