### ISSUE TITLE
Renaming js to ts requires server restart

### ISSUE THREAD

**Issue by rsmith-cs-ux** [typed-ember/ember-cli-typescript#1336]
Hi there!

While running ember s, whenever I generate a new component everything works just fine and the changes are automatically detected. But when I rename the file from .js to .ts (because I'm using typescript) I have to restart the server because the changes break everything. It would be great if it could detect the change and handle it properly.  I filed the issue with ember-cli and they said it sounded like an issue with ember-cli-typescript (https://github.com/ember-cli/ember-cli/issues/9345).

Thanks!

#### User story
As a user, I want to rename files from `.js` to `.ts` without having to restart the ember server.

**Comment by chriskrycho** [comment]
I believe this is related to #724, and *should* be a function of the ember-cli-babel build, not anything ember-cli-typescript does anymore, assuming you're on a sufficiently recent version of both ember-cli-babel and ember-cli-typescript: does this reproduce on latest of both? If so, it's actually a fundamental limitation in the way the build pipeline works. If not, I'm *very* curious what the issue would be.

cc. @rwjblue

**Comment by chriskrycho** [comment]
We now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tsc` directly on their projects. Accordingly, although this *should not* be an issue, even if it is we will not be addressing it, as we are moving this package into maintenance mode. Thanks!
