### ISSUE TITLE
Package `fs-extra@^9.0.1` requires Node v10 or greater, but Ember 2.18 supports Node versions up to only v9.

### ISSUE THREAD

**Issue by coddingtonbear** [typed-ember/ember-cli-typescript#1338]
When attempting to install `ember-cli-typescript` for use with an Ember 2.18 project, the following error is displayed:

```
# ember install ember-cli-typescript@latest
Installed packages for tooling via npm.
Unexpected token {
/app/node_modules/ember-cli-typescript/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/ember-cli-typescript/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
r
```

This is apparently caused by this fairly recent change to `package.json`: https://github.com/typed-ember/ember-cli-typescript/blob/7acb88fe6da9a6ac03ead8e18e9e96b3e0ff7fc9/package.json#L46 pinning the build to `^9.0.1` of `fs-extra` from the earlier pin to `^8.0.0`.  Unfortunately, [fs-extra dropped support for versions of Node earlier than v10 with their release of `9.0.0`](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#user-content-breaking-changes) and Ember 2.18 does not support Node v10.

I'm not super super clear that you folks intend to continue supporting this package on Ember 2.x; so forgive me if you don't!  Just thought I should let you know that I ran into this problem today when trying to install this on a fairly old ember build of mine.

Cheers!

**Comment by chriskrycho** [comment]
Thank you for reporting this, @coddingtonbear! We do in fact *not* officially support Ember 2.x at this time—but this actually reminds me that we need to see if we can get `fs-extra` out of our build entirely: it really isn't doing a lot as of recent Node versions. Removing it might help here, or it might not, but it'd be a win for us in any case. (I've already got a WIP branch that does that on the blueprints repo.)

**Comment by chriskrycho** [comment]
(Note: I'm going to close this as "resolved" given the above answer, but feel free to keep conversing here!)
