### ISSUE TITLE
Work out of the box

### ISSUE THREAD

**Issue by dwickern** [typed-ember/ember-cli-typescript#136]
Running `ember new` followed by `ember install ember-cli-typescript` should work without any compiler errors.

`@types/ember-qunit` is missing, which causes a compiler error when you try to write a test -- #135.

`@types/ember-data` is included but you still get compiler errors since no registry is defined. We should add the [catch-all registry snippet](https://github.com/typed-ember/ember-cli-typescript#fixing-the-ember-data-error-ts2344-problem) to the blueprint.

For reference, these are the dependencies added by ember-cli 3.0 to a fresh `ember new`:
- broccoli-asset-rev
- ember-ajax
- ember-cli
- ember-cli-app-version
- ember-cli-babel
- ember-cli-dependency-checker
- ember-cli-eslint
- ember-cli-htmlbars
- ember-cli-htmlbars-inline-precompile
- ember-cli-inject-live-reload
- ember-cli-qunit
- ember-cli-shims
- ember-cli-sri
- ember-cli-uglify
- ember-data
- ember-export-application-global
- ember-load-initializers
- ember-maybe-import-regenerator
- ember-resolver
- ember-source
- ember-welcome-page
- eslint-plugin-ember
- loader.js

And for `ember addon`:
- broccoli-asset-rev
- ember-ajax
- ember-cli
- ember-cli-dependency-checker
- ember-cli-eslint
- ember-cli-htmlbars
- ember-cli-htmlbars-inline-precompile
- ember-cli-inject-live-reload
- ember-cli-qunit
- ember-cli-shims
- ember-cli-sri
- ember-cli-uglify
- ember-disable-prototype-extensions
- ember-export-application-global
- ember-load-initializers
- ember-maybe-import-regenerator
- ember-resolver
- ember-source
- ember-source-channel-url
- ember-try
- eslint-plugin-ember
- eslint-plugin-node
- loader.js

**Comment by dfreeman** [comment]
May or may not matter, but addons have a [slightly different set of OOB dependencies](https://github.com/ember-cli/ember-addon-output/blob/master/package.json). The main noteworthy difference is that they don't get `ember-data` by default.

**Comment by chriskrycho** [comment]
I'm going to go ahead and cut 1.1.4 now b/c of the stuff Toran and I ran into, but think we should get this into a 1.1.5 later this week.

**Comment by chriskrycho** [comment]
Similarly, we should probably check if `ember-qunit` or `ember-mocha` are installed and automatically install those typings as well.
