### ISSUE TITLE
Add types for `@ember/component/template-only`

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#1360]
### Which package(s) does this enhancement pertain to?

  - [x] @types/ember__component

### Please write a user story for this feature

Follow the form

> *As a **role**, I want **feature** so that **reason**.*

As an app or addon author (*especially* an addon author) working in Ember Octane, I want to be able to import `templateOnly` from `'@ember/component/template-only'`, since addons cannot rely on template colocation to be enabled during the Ember 3.x lifecycle.

**Comment by jamescdavis** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49280
