### ISSUE TITLE
New type errors with ember and ember-data 3.24 releases

### ISSUE THREAD

**Issue by kpfefferle** [typed-ember/ember-cli-typescript#1397]
### Which package(s) does this problem pertain to?
  - [x] @types/ember
  - [x] @types/ember-data

### What are instructions we can follow to reproduce the issue?
```sh
npm i -g ember-cli@3.24.0

ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember install @types/ember-data

ember serve
```

### Now about that bug. What did you expect to see?

I'd expect to see the app build with no errors.

### What happened instead?

```sh
node_modules/@types/ember/index.d.ts:446:46 - error TS2339: Property 'htmlSafe' does not exist on type 'typeof import("[REDACTED]/node_modules/@ember/string/index")'.

446         const htmlSafe: typeof EmberStringNs.htmlSafe;
                                                 ~~~~~~~~

node_modules/@types/ember/index.d.ts:447:48 - error TS2339: Property 'isHTMLSafe' does not exist on type 'typeof import("[REDACTED]/node_modules/@ember/string/index")'.

447         const isHTMLSafe: typeof EmberStringNs.isHTMLSafe;
                                                   ~~~~~~~~~~

node_modules/@types/ember-data/index.d.ts:137:31 - error TS2344: Type 'TransformRegistry[K]' does not satisfy the constraint 'string | number | boolean | Date | Transform'.
  Type 'string | number | boolean | {} | any[] | Date' is not assignable to type 'string | number | boolean | Date | Transform'.
    Type '{}' is not assignable to type 'string | number | boolean | Date | Transform'.
      Type '{}' is missing the following properties from type 'Transform': serialize, deserialize, get, getProperties, and 17 more.
        Type 'TransformRegistry[K]' is not assignable to type 'Transform'.
          Type 'string | number | boolean | {} | any[] | Date' is not assignable to type 'Transform'.
            Type 'string' is not assignable to type 'Transform'.

137         options?: AttrOptions<TransformRegistry[K]>
                                  ~~~~~~~~~~~~~~~~~~~~
```

**Comment by gwak** [comment]
The `htmlSafe` function seem to have moved from 
```ts
import { htmlSafe } from '@ember/string';
```
to 
```ts
import { htmlSafe } from '@ember/template';
```

**Comment by jamescdavis** [comment]
Importing `htmlSafe` from `@ember/string` is deprecated, but should continue to work for now. This PR adds it back to the types in a way that it compatible with the `@ember/string` *package* that is a dependency of ember-data 3.24: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50653

**Comment by jamescdavis** [comment]
Some context: There was an issue were the types shipped with  the `@ember/string` *package* (which is a new dep of `ember-data` as of 3.24) override the types defs from DefinitelyTyped. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50545 removed `htmlSafe` and `isHTMLSafe` from those type defs because of this issue.

**Comment by jamescdavis** [comment]
Also: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50652 should fix the issue with transform types.

**Comment by jamescdavis** [comment]
All issues should be resolved in latest @types/ember__string and @types/ember-data (please reopen if not).

**Comment by aaronucsd** [comment]
Since @types/ember__string is a dep in @types/ember-data. Should we put out a PR for this?

**Comment by aaronucsd** [comment]
I updated @types/ember-data  to the latest but we aren't using @types/ember__string  directly. Is that a dependency in another dep? I don't think it's in `ember-data`. Should we have a PR for this?
