### ISSUE TITLE
Import Ember's namespace as a Type-Only import

### ISSUE THREAD

**Issue by MrChocolatine** [typed-ember/ember-cli-typescript#1398]
Since the project runs with TypeScript v4.0.5
https://github.com/typed-ember/ember-cli-typescript/blob/ecb513be474b6db641c0aa36b176a8351eb4ed14/package.json#L126

should we import Ember's namespace as a [Type-Only import](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)?

https://github.com/typed-ember/ember-cli-typescript/blob/ecb513be474b6db641c0aa36b176a8351eb4ed14/ts/blueprints/ember-cli-typescript/index.js#L6

**Suggestion**

```ts
import type Ember from 'ember';
```

**Comment by chriskrycho** [comment]
Hmm. I'd be surprised if that even works correctly. Namespaces are properly *value* types, and folks still regularly need to use it to refer to e.g. `Ember.testing`.
