### ISSUE TITLE
Documentation about Routes is truncated

### ISSUE THREAD

**Issue by MrChocolatine** [typed-ember/ember-cli-typescript#1417]
From https://github.com/typed-ember/ember-cli-typescript/blob/22abe759e1bdea79d06afe2c0e77f7e10efcf055/docs/ember/routes.md#L36-L38

> ... the type we will have available as `@model` in the template and as `this.model` on a controller. This in turn allows us to use

Can the authors finish the text please?

Thanks!

**Comment by chriskrycho** [comment]
Fixed a little while back (in e30f6f5ea).
