### ISSUE TITLE
Add types for Destroyable

### ISSUE THREAD

**Issue by steveszc** [typed-ember/ember-cli-typescript#1419]
### Which package(s) does this enhancement pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [x] Other
  - [ ] I don't know

### Please write a user story for this feature

As an addon OR app author,
I want type definitions for Ember Destroyables available on DefinitelyTyped, 
so that I can use Destroyables in my typescript ember app or addon.

Types currently exist for Destroyables in the destroyables polyfill. They need to be added to DefinitelyTyped now that the Destroyables API is part of ember as of 3.22
https://github.com/ember-polyfills/ember-destroyable-polyfill/blob/master/index.d.ts

**Comment by chriskrycho** [comment]
Closing since we landed those. Thanks!
