### ISSUE TITLE
Error: Generic type 'AttrOptions<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by gabrieltrita** [typed-ember/ember-cli-typescript#1465]
ember-cli: 3.20.2
node: 12.22.0
os: darwin x64

tsc version: Version 4.5.4

yarn list --pattern 'ember-cli-typescript'
├─ @ember-data/adapter@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/canary-features@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/debug@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/model@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/private-build-infra@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/record-data@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/serializer@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @ember-data/store@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ @glimmer/component@1.0.4
│  └─ ember-cli-typescript@3.0.0
├─ @hwetda/ember-symbols@1.0.1
│  └─ ember-cli-typescript@3.1.4
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@4.2.1
├─ ember-concurrency-decorators@2.0.3
│  └─ ember-cli-typescript@3.1.4
├─ ember-data@3.20.5
│  └─ ember-cli-typescript@3.1.4
├─ ember-load-initializers@2.1.2
│  └─ ember-cli-typescript@2.0.2
└─ ember-modifier@2.1.2
   └─ ember-cli-typescript@3.1.4

npm list ember-cli-typescript ember-cli-typescript-blueprints
├─┬ @glimmer/component@1.0.4
│ └── ember-cli-typescript@3.0.0
├─┬ @hwetda/ember-symbols@1.0.1
│ └── ember-cli-typescript@3.1.4
├── ember-cli-typescript-blueprints@3.0.0
├── ember-cli-typescript@4.2.1
├─┬ ember-concurrency-decorators@2.0.3
│ └── ember-cli-typescript@3.1.4
├─┬ ember-data@3.20.5
│ ├─┬ @ember-data/adapter@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/debug@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/model@3.20.5
│ │ ├─┬ @ember-data/canary-features@3.20.5
│ │ │ └── ember-cli-typescript@3.1.4
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/private-build-infra@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/record-data@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/serializer@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/store@3.20.5
│ │ └── ember-cli-typescript@3.1.4
│ └── ember-cli-typescript@3.1.4
├─┬ ember-fetch@8.1.1
│ └── ember-cli-typescript@4.2.1 deduped
├─┬ ember-load-initializers@2.1.2
│ └── ember-cli-typescript@2.0.2
└─┬ ember-modifier@2.1.2
  └── ember-cli-typescript@3.1.4

"ember-cli-typescript": "^4.2.1",
"ember-cli-typescript-blueprints": "^3.0.0",

##### Reproduction Case
Build error:
```
node_modules/@ember-decorators/data/index.d.ts:32:14 - error TS2314: Generic type 'AttrOptions<T>' requires 1 type argument(s).
(options?: DS.AttrOptions): ComputedDecorator<any>;
```
Can anyone tell me why this error when trying to build the project?

**Comment by chriskrycho** [comment]
@gabrieltrita did you get it figured out?
