### ISSUE TITLE
Make working with linked TS addons easier?

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/ember-cli-typescript#147]
Currently there's a fair amount of [manual config](https://github.com/typed-ember/ember-cli-typescript#linking-addons) necessary for working with linked TypeScript addons. It might be useful to introduce a command like `ember ts:link-types <addon-name>` (and its dual) to automate this process.

**Comment by jamescdavis** [comment]
So this command would add the appropriate stuff to `paths` and `include`? It could also check that `isDevelopingAddon() === true`, but probably shouldn't modify the addon automatically?

**Comment by dfreeman** [comment]
> So this command would add the appropriate stuff to paths and include?

👍 

> It could also check that isDevelopingAddon() === true, but probably shouldn't modify the addon automatically?

Agreed—just issuing a warning if it returns false would be great.

**Comment by chriskrycho** [comment]
We now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tsc` directly on their projects. Accordingly, the “best” way to make working with add-ons is to use the normal flows for projects configured that way!
