### ISSUE TITLE
Types for ember-test-helpers are confusing

### ISSUE THREAD

**Issue by mydea** [typed-ember/ember-cli-typescript#1470]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [x] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

The whole situation around types for @ember/test-helpers is rather confusing to me.
There is `@types/ember__test-helpers`, as well as `@types/ember-test-helpers`.

This leads to some confusion. Also, especially with the v4 type update, `@types/ember-test-helpers` seems to not have been updated anymore (it still relies on `@types/ember@^3`), which leads to a bunch of issues with conflicting types for me.

At the end, I could resolve it by removing `@types/ember-test-helpers` and just using `@types/ember__test-helpers@^4`. This also means you have to import everything from `@ember/test-helpers` - previously, there have been some things like the TestContext that you used to have to import from `ember-test-helpers` instead. This is also still that way in the docs.

IMHO it probably makes sense to remove all mentions and traces of `ember-test-helpers` and `@types/ember-test-helpers`

**Comment by chriskrycho** [comment]
Your recommendation is correct. (The ecosystem was confusing! Our types just had to try to represent it. 😩)

- You should remove `ember-test-helpers` and corresponding types from your app entirely, switching entirely to `@ember/test-helpers` and `@types/ember__test-helpers`.
- We need to update the docs to stop referencing `ember-test-helpers`.
