### ISSUE TITLE
@types/ember__utils: `typeOf()` won't accept object type

### ISSUE THREAD

**Issue by charlesfries** [typed-ember/ember-cli-typescript#1475]
Seeing this error after bumping `@types/ember__utils` from `^3.16.2` to `^4.0.0`

### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [X] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample
cd sample
ember install ember-cli-typescript
ember g component -gc export
```

Add the following to the component class:

```js
import Component from '@glimmer/component';
import { assert } from '@ember/debug';
import { typeOf } from '@ember/utils';

export interface ExportComponentArgs {
  schema: Record<string, unknown>;
}

export default class ExportComponent extends Component<ExportComponentArgs> {
  constructor(owner: unknown, args: ExportComponentArgs) {
    super(owner, args);
    assert('<Export />: Must pass a schema object', typeOf(this.args.schema) === 'object'); // This condition will always return 'false' since the types '"function"' and '"object"' have no overlap.
  }
}
```

On the `assert` line, I am seeing the following TypeScript type error:

```
This condition will always return 'false' since the types '"function"' and '"object"' have no overlap.
```

`schema` is a `Record` type, but `typeOf()` thinks it should a function. Anyone know why?

**Comment by chriskrycho** [comment]
Ugh. I hate that type so much. I thought I had covered all the issues with it when making the updates, but apparently not. Thank you for the report! I'll try to poke at it next week.

**Comment by chriskrycho** [comment]
@charlesfries is this *not* still a problem?

**Comment by charlesfries** [comment]
I ended up rm -rf ing `package-lock.json` and `node_modules` after reading #1474 and the issue went away.

**Comment by chriskrycho** [comment]
Oh! That's really, *really* good to hear. 😅 (I hate this particular type.)
