### ISSUE TITLE
Exclude docs-only changes from build

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#149]
We don't need to run a build for every time someone fixes a link or something in Markdown files. Can we disable that in Travis and AppVeyor?

**Comment by dfreeman** [comment]
It looks like AppVeyor supports this, but as far as I can tell [Travis doesn't](https://github.com/travis-ci/travis-ci/issues/6301). Committers can include `[ci skip]` in their commit messages, but I'm not sure if there's a way we can force builds not to run from this end other than manually canceling them.

**Comment by jamescdavis** [comment]
#154 is a work-around for Travis that, at least, shortens the build time significantly by skipping all `install` and `script` tasks if only Markdown files have changed.
