### ISSUE TITLE
[docs] add section to configuration about working in monorepos

### ISSUE THREAD

**Issue by hmajoros** [typed-ember/ember-cli-typescript#1499]
running `ember install ember-cli-typescript` will automatically add `ember-cli-typescript` as a dependency in your top level package.json, but in a monorepo you may need to additionally add `ember-cli-typescript` into the top level package for any apps in your monorepo. Without this step, you will never kick off typechecking as part of the build because this conditional will never be met: 

https://github.com/typed-ember/ember-cli-typescript/blob/22abe759e1bdea79d06afe2c0e77f7e10efcf055/ts/addon.ts#L31

We should add a note to the docs somewhere (likely during the installation/configuration?) to remind folks working in a mono-repo that they'll need to add `ember-cli-typescript` as a devDependency in the top level package.json of any app inside their mono-repo.

**Comment by chriskrycho** [comment]
Since we're moving away from recommending `ember-cli-typescript`, I'm going to close this (and trust that the existence of the issue itself may help anyone who runs into it). Thanks!
