### ISSUE TITLE
If extended from AdapterError, InvalidError, super can be called only with 1 argument

### ISSUE THREAD

**Issue by dsafonov-grid** [typed-ember/ember-cli-typescript#1501]
### Which package(s) does this problem pertain to?
  - [+] @types/ember__object
  - [+] @types/ember-data
  
### What are instructions we can follow to reproduce the issue?
Extend AdapterError or InvalidError in your project, and try calling super()
You will see the following error
<img width="459" alt="Screen Shot 2022-04-28 at 16 03 40" src="https://user-images.githubusercontent.com/82807060/165749884-0b4ec98d-2025-44a1-8f8e-7f78ab132ebd.png">

##### Reproduction Case

You can see TS error when calling super()
Link to sandbox: https://codesandbox.io/s/my-app-forked-m8xqlt?file=/app/components/x-foo.ts

### Now about that bug. What did you expect to see?
"I expected to be able to call super with 2 arguments without TS highlighting errors"

### What happened instead?
"TypeScript seems to think that there is only ability to call super with 0-1 argument"

#### My thoughts

This is happening because in node_modules/@types/ember-data/index.d.ts AdapterError extends Ember.Object, then
Ember.Object extends EmberObjectNs.default
EmberObjectNs.default extends CoreObject, which indeed has constructor like this 
```js
constructor(properties?: object);
```

Also I don't see the point of typing invalid error like 
```js
class InvalidError extends AdapterError {
        constructor(errors: any[]);
    }
```
Once we extend InvalidError we once again can't pass message as 2nd argument.

#### Proposed solution
I assume that it is more convenient to have types like 
```js
 class AdapterError extends Ember.Object {
        constructor(errors: any[], message?: string);
    }
 class InvalidError extends AdapterError {}
```

**Comment by chriskrycho** [comment]
Just saw this – thanks for opening an issue about it, and sorry it was frustrating.

However, two things here:

1. TypeScript is actually telling you the appropriate thing! If you try to call a `super` with the wrong arguments, this is exactly what should happen. The types we supply are the types that match what the actual runtime behavior of the custom error types is. (They could be buggy, but no one has reported that previously so I'd be a bit surprised!)

2. Additionally, these error types should simply go away; you definitely don't want to subclass them or rely on that. If you need custom errors, you should extend directly from `Error` instead.
