### ISSUE TITLE
Interface 'NativeArray<T>' cannot simultaneously extend types 'GlobalArray<T>' and 'MutableArray<T>'.   Named property 'setEach' of types 'GlobalArray<T>' and 'MutableArray<T>' are not identical.

### ISSUE THREAD

**Issue by lolmaus** [typed-ember/ember-cli-typescript#1505]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__array

### What are instructions we can follow to reproduce the issue?

```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
node node_modules/typescript/bin/tsc --noEmit # lint TypeScript
```

### Reproduction Case

**Link:** https://github.com/lolmaus/lolma.us/tree/nativearray-issue

```
npm run lint:tsc
```

### Now about that bug. What did you expect to see?

No error.

### What happened instead?

```
node_modules/@types/ember-test-helpers/node_modules/@types/ember__array/-private/native-array.d.ts:16:11 - error TS2320: Interface 'NativeArray<T>' cannot simultaneously extend types 'GlobalArray<T>' and 'MutableArray<T>'.
  Named property 'sortBy' of types 'GlobalArray<T>' and 'MutableArray<T>' are not identical.

16 interface NativeArray<T> extends GlobalArray<T>, MutableArray<T>, Observable, Copyable {
             ~~~~~~~~~~~
```

**Comment by chriskrycho** [comment]
Thanks for opening this! It's unclear exactly why this is happening and *not* tripping up otherwise, but clearly something in the definitions is messed up!

**Comment by lolmaus** [comment]
I installed typescript with `ember i ember-cli-typescript` without `@latest`, which gave me `^3.0.0` instead of `^5.0.0` for some reason. Why?

This issue does not happen with latest `ember-cli-typescript`.
