### ISSUE TITLE
No declaration files output during precompile

### ISSUE THREAD

**Issue by csprocket777** [typed-ember/ember-cli-typescript#1522]
### Please paste the output of `ember -v` here
ember-cli: 3.25.3
node: 16.13.1
os: darwin arm64

### Please paste the output of `tsc -v` here
Version 4.7.3

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here
├─ @ember-data/private-build-infra@3.26.0
│  └─ ember-cli-typescript@3.1.4
├─ @glimmer/component@1.1.2
│  └─ ember-cli-typescript@3.0.0
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@4.2.1
├─ ember-concurrency-decorators@2.0.3
│  └─ ember-cli-typescript@3.1.4
├─ ember-load-initializers@2.1.2
│  └─ ember-cli-typescript@2.0.2
└─ ember-modifier@3.2.7
   └─ ember-cli-typescript@5.1.0

├─┬ @glimmer/component@1.1.2
│ └── ember-cli-typescript@3.0.0
├─┬ ember-cli-addon-docs@4.2.2
│ ├─┬ @ember/legacy-built-in-components@0.4.1
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ ember-fetch@8.1.1
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ ember-keyboard@7.0.1
│ │ └─┬ ember-modifier@3.2.7
│ │   └── ember-cli-typescript@5.1.0
│ └─┬ ember-router-scroll@4.1.2
│   └─┬ ember-app-scheduler@7.0.1
│     └── ember-cli-typescript@4.2.1 deduped
├── ember-cli-typescript-blueprints@3.0.0
├── ember-cli-typescript@4.2.1
├─┬ ember-data@3.26.0
│ ├─┬ @ember-data/adapter@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/debug@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/model@3.26.0
│ │ ├─┬ @ember-data/canary-features@3.26.0
│ │ │ └── ember-cli-typescript@4.2.1 deduped
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/private-build-infra@3.26.0
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/record-data@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/serializer@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/store@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ └── ember-cli-typescript@4.2.1 deduped
├─┬ ember-load-initializers@2.1.2
│ └── ember-cli-typescript@2.0.2
└─┬ ember-power-select@5.0.4
  ├─┬ ember-basic-dropdown@4.0.5
  │ └── ember-cli-typescript@4.2.1 deduped
  ├── ember-cli-typescript@4.2.1 deduped
  └─┬ ember-concurrency-decorators@2.0.3
    └── ember-cli-typescript@3.1.4

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

{
  "compilerOptions": {
    "target": "es2020",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": true,
    "strictNullChecks": false,
    "strictPropertyInitialization": false,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": true,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "experimentalDecorators": true,
    "paths": {
      "dummy/tests/*": [
        "tests/*"
      ],
      "dummy/*": [
        "tests/dummy/app/*",
        "app/*"
      ],
      "ember-cui": [
        "addon"
      ],
      "ember-cui/*": [
        "addon/*"
      ],
      "ember-cui/test-support": [
        "addon-test-support"
      ],
      "ember-cui/test-support/*": [
        "addon-test-support/*"
      ],
      "*": [
        "types/*"
      ]
    }
  },
  "include": [
    "app/**/*",
    "addon/**/*",
    "tests/**/*",
    "types/**/*",
    "test-support/**/*",
    "addon-test-support/**/*"
  ]
}

  
</pre></details>

<details><summary><b>My tslint.json or eslint.json</b></summary><pre>

  

</pre></details>

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support

ember ts:precompile

```

### Now about that bug. What did you expect to see?
I've written an addon using ember-cli-typescript and when I try to check the declaration files by running `ember ts:precompile`, nothing is output to the command line as a result and no files appear to be output either.

I expected to fine declaration files output to the project.

I feel as though I'm doing something wrong. Can someone point me in the right direction?

### What happened instead?
I could not find any new declaration files anywhere and nothing was output to the command line.

**Comment by charlesfries** [comment]
Fyi afaik no declaration files will be generated for a project without .ts files, like in the case of your reproduction. Are you still seeing this issue after generating a component/helper/etc?

**Comment by csprocket777** [comment]
ALL of my component files are 100% `.ts`.

**Comment by csprocket777** [comment]
Ok. I figured out my issue. For my future self and anyone else, here's what was going on in my instance.

I had `"strictNullChecks": false,` in my `tsconfig.json` file. This meant that it wasn't checking for how I was handling and using null values throughout my code. From my current understanding about Typescript, it doesn't like handling `null` values. [Correct me if I'm wrong, or elaborate please]

So in cases where something might not exist or have a value yet wasn't being handled and in some cases I wasn't providing types for my temporary variables inside functions.

Setting that option to `"strictNullChecks": true,` in `tsconfig.json` and then running `ember ts:precompile` started showing me the errors in my code that the was causing the precompile to fail. As I fixed those errors, the declaration files started to appear. And they appear, as indicated in the docs, in the root of the project.
