### ISSUE TITLE
Can subclass declarations include the inherited aspects of the base class?

### ISSUE THREAD

**Issue by csprocket777** [typed-ember/ember-cli-typescript#1523]
### Please paste the output of `ember -v` here
ember-cli: 3.25.3
node: 16.13.1
os: darwin arm64

### Please paste the output of `tsc -v` here
Version 4.7.3

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here
├─ @ember-data/private-build-infra@3.26.0
│  └─ ember-cli-typescript@3.1.4
├─ @glimmer/component@1.1.2
│  └─ ember-cli-typescript@3.0.0
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@4.2.1
├─ ember-concurrency-decorators@2.0.3
│  └─ ember-cli-typescript@3.1.4
├─ ember-load-initializers@2.1.2
│  └─ ember-cli-typescript@2.0.2
└─ ember-modifier@3.2.7
   └─ ember-cli-typescript@5.1.0

├─┬ @glimmer/component@1.1.2
│ └── ember-cli-typescript@3.0.0
├─┬ ember-cli-addon-docs@4.2.2
│ ├─┬ @ember/legacy-built-in-components@0.4.1
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ ember-fetch@8.1.1
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ ember-keyboard@7.0.1
│ │ └─┬ ember-modifier@3.2.7
│ │   └── ember-cli-typescript@5.1.0
│ └─┬ ember-router-scroll@4.1.2
│   └─┬ ember-app-scheduler@7.0.1
│     └── ember-cli-typescript@4.2.1 deduped
├── ember-cli-typescript-blueprints@3.0.0
├── ember-cli-typescript@4.2.1
├─┬ ember-data@3.26.0
│ ├─┬ @ember-data/adapter@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/debug@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/model@3.26.0
│ │ ├─┬ @ember-data/canary-features@3.26.0
│ │ │ └── ember-cli-typescript@4.2.1 deduped
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/private-build-infra@3.26.0
│ │ └── ember-cli-typescript@3.1.4
│ ├─┬ @ember-data/record-data@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/serializer@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ ├─┬ @ember-data/store@3.26.0
│ │ └── ember-cli-typescript@4.2.1 deduped
│ └── ember-cli-typescript@4.2.1 deduped
├─┬ ember-load-initializers@2.1.2
│ └── ember-cli-typescript@2.0.2
└─┬ ember-power-select@5.0.4
  ├─┬ ember-basic-dropdown@4.0.5
  │ └── ember-cli-typescript@4.2.1 deduped
  ├── ember-cli-typescript@4.2.1 deduped
  └─┬ ember-concurrency-decorators@2.0.3
    └── ember-cli-typescript@3.1.4

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

{
  "compilerOptions": {
    "target": "es2020",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": false,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": true,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "experimentalDecorators": true,
    "paths": {
      "dummy/tests/*": [
        "tests/*"
      ],
      "dummy/*": [
        "tests/dummy/app/*",
        "app/*"
      ],
      "ember-cui": [
        "addon"
      ],
      "ember-cui/*": [
        "addon/*"
      ],
      "ember-cui/test-support": [
        "addon-test-support"
      ],
      "ember-cui/test-support/*": [
        "addon-test-support/*"
      ],
      "*": [
        "types/*"
      ]
    }
  },
  "include": [
    "app/**/*",
    "addon/**/*",
    "tests/**/*",
    "types/**/*",
    "test-support/**/*",
    "addon-test-support/**/*"
  ]
}

  
</pre></details>

### Now about that bug. What did you expect to see?
I have components that are subclasses of a base component class. I was hoping that when the declaration files were created that it would allow the code completion hints in programs like Visual Studio Code to also show the inherited properties and functions of the base class.

### What happened instead?
When using Visual Studio Code, none of the inherited aspects of the base component class appear in the suggestions, only the aspects of the specific class appear.

**Comment by chriskrycho** [comment]
Can you share some actual code samples that aren't working? The thing you're describing absolutely works (and is not Ember-specific, gladly), so it's likely there's something quirky going on!

**Comment by csprocket777** [comment]
I thought it should as well, hence my confusion. The compiled code certainly does inherit from the base class but doesn't appear to contain that information in the declaration files to support code completion in VSCode.

Here's an example of my base and individual component class, trimmed down:

```javascript

/**
 * @interface
 */
export interface EmberCuiBaseComponentArgs {
// ...interface here...
}



/**
 * The base component for all Ember-CUI components
 * 
 * @class EmberCuiBaseComponent
 * @main EmberCui
 * @extends Ember.Component
 * @interface EmberCuiBaseComponentArgs
 * @export default
 * @public
 */
export default class EmberCuiBaseComponent<Args extends EmberCuiBaseComponentArgs = EmberCuiBaseComponentArgs> extends Component<Args> {
// ...base component class...
}
```

**Extended class:**
```javascript
/**
 * @module EmberCuiLabel
 * @class EmberCuiLabel
 */
import EmberCuiBaseComponent from './ember-cui-base-component';
import { EmberCuiBaseComponentArgs } from './ember-cui-base-component';

/**
 * @interface
 */
export interface EmberCuiLabelArgs extends EmberCuiBaseComponentArgs {
// ...extended interface here...
}

/**
 * <aside class="small">
 *  <strong>Base Class:</strong> <a href="./ember-cui-base-component">EmberCuiBaseComponent</a><br/>
 *  <strong>Cisco-UI Spec:</strong>
 * </aside>
 *
 * @class EmberCuiLabel
 * @extends {EmberCuiBaseComponent}
 * @implements {EmberCuiLabelArgs}
 * @implements {EmberCuiBaseComponentArgs}
 * @export default
 */

export default class EmberCuiLabel<Args extends EmberCuiLabelArgs = EmberCuiLabelArgs> extends EmberCuiBaseComponent<Args> implements EmberCuiBaseComponentArgs {
// ...extended component here...
}
```

**Comment by csprocket777** [comment]
Alright, disregard. I realized through a chat in Discord that I'm expecting this level of auto-completion to work in the template and that's not something that ELS supports. It only supports auto-completion of immediate members in the class, not the parent class.
