### ISSUE TITLE
Typechecker eats 70% of CPU when idle

### ISSUE THREAD

**Issue by runspired** [typed-ember/ember-cli-typescript#1524]
this guy: https://github.com/typed-ember/ember-cli-typescript/blob/master/ts/lib/typechecking/worker/launch.ts

unsure what it's doing that requires that.

**Comment by chriskrycho** [comment]
@runspired a couple questions here:

1. Can you reproduce this consistently, and across different machines and projects?
2. What happens if you have `tsc --watch` running in the same project where you’re seeing this?

**Comment by chriskrycho** [comment]
We now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tsc` directly on their projects. Accordingly, although this *should not* be an issue, even if it is we will not be addressing it, as we are moving this package into maintenance mode. Thanks!
