### ISSUE TITLE
Make sure docs are up to date for Signature usage

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#1529]
I did a pass a while back which caught some of this, but as [this discussion on Discourse](https://discuss.emberjs.com/t/component-arguments-and-typescript-whats-the-right-approach/19761) indicates, we have at least one spot (and, more likely, a number of spots) in need of updating to match how we model the world with `Signature` in view, including specifically how to refer to the `Args` type in a `constructor`.

**Comment by roomman** [comment]
Aa promised, added a PR for this: https://github.com/typed-ember/ember-cli-typescript/pull/1530. 👍🏻
