### ISSUE TITLE
Broken with Embroider 1.9.0

### ISSUE THREAD

**Issue by rwwagner90** [typed-ember/ember-cli-typescript#1540]
### Please paste the output of `ember -v` here

ember-cli: 4.8.0
node: 14.18.2
os: darwin arm64

### Please paste the output of `tsc -v` here

Version 4.8.4

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here

├─ @glimmer/component@1.1.2
│  └─ ember-cli-typescript@3.0.0
├─ ember-cli-typescript-blueprint-polyfill@0.1.0
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@5.2.1
├─ ember-fetch@8.1.2
│  └─ ember-cli-typescript@4.2.1
└─ ember-load-initializers@2.1.2
   └─ ember-cli-typescript@2.0.2

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

  
  
</pre></details>

<details><summary><b>My tslint.json or eslint.json</b></summary><pre>

  

</pre></details>

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support

>> Your Instructions Go Here <<

```

##### Reproduction Case
If you can, please try to fork [this codesandbox](https://codesandbox.io/s/github/mike-north/ember-new-output/tree/ts), and give us an example that demonstrates the problem. Paste the link below so that we can see what's going on

**Link: ** <your link here>

### What happened instead?

Any components with TS files will fail to find anything in templates like `this.foo` it will always be undefined with Embroider 1.9.0

**Comment by dfreeman** [comment]
This is a known bug in Embroider 1.9 unrelated to ember-cli-typescript. [A fix](https://github.com/embroider-build/embroider/pull/1273) has been merged but as far as I know not released yet.
