### ISSUE TITLE
"@ember/test-helpers/setup-rendering-context"' has no exported member named 'rerender'. Did you mean 'render'?

### ISSUE THREAD

**Issue by aburto22** [typed-ember/ember-cli-typescript#1543]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [x] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember serve # Start dev server
```

### Now about that bug. What did you expect to see?
I expected the dev server to run.

### What happened instead?
I got the following error:

```
node_modules/@types/ember__test-helpers/index.d.ts:56:18 - error TS2724: '"@ember/test-helpers/setup-rendering-context"' has no exported member named 'rerender'. Did you mean 'render'?

56 export { render, rerender, clearRender } from '@ember/test-helpers/setup-rendering-context';
                    ~~~~~~~~

  node_modules/@ember/test-helpers/public-types/@ember/test-helpers/setup-rendering-context.d.ts:34:25
    34 export declare function render(templateOrComponent: TemplateFactory | ComponentInstance, options?: RenderOptions): Promise<void>;
                               ~~~~~~

    'render' is declared here.
```

**Comment by chriskrycho** [comment]
Sorry for the *long*-delayed response; this should be resolved by updating to a current version of `@ember/test-helpers` which ships its own types. Thanks!
