### ISSUE TITLE
bug: when `moduleName` and `package.name` differ, types will not be generated by default

### ISSUE THREAD

**Issue by hmajoros** [typed-ember/ember-cli-typescript#1547]
not sure if worth fixing, since (1) this library is basically no longer supported, and (2) I doubt many people have differing package & module names. HOWEVER: the blueprints will generate your `tsconfig.paths` mapping based on the `package.name`, and when we call [copyDeclarations](https://github.com/typed-ember/ember-cli-typescript/blob/master/ts/lib/utilities/copy-declarations.ts#L12), the paths mapping never finds a place to copy the types, since we're using moduleName:
```
    if (
      logicalPath.startsWith(`${packageName}/`) &&
      logicalPath.indexOf('/*') === logicalPath.length - 2
    ) {
```

if anyone encounters this issue, the fix is to change your internal tsconfig paths mapping to use the `moduleName`, not the `package.name`

**Comment by chriskrycho** [comment]
Correction: the library is *absolutely* supported; we just expect the need for it to diminish substantially as the community moves away from v1 addons!
