### ISSUE TITLE
Newly generated component is not buildable: Property 'element' does not exist on type 'TestContext'

### ISSUE THREAD

**Issue by Polve** [typed-ember/ember-cli-typescript#1564]
### Please paste the output of `ember -v` here

ember-cli: 5.1.0
node: 18.15.0
os: linux x64

### Please paste the output of `tsc -v` here

Version 5.1.6

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here

├─┬ @glimmer/component@1.1.2
│ └── ember-cli-typescript@3.0.0
├── ember-cli-typescript@5.2.1
├─┬ ember-fetch@8.1.2
│ └── ember-cli-typescript@4.2.1
├─┬ ember-load-initializers@2.1.2
│ └── ember-cli-typescript@2.0.2
└─┬ tracked-built-ins@3.1.1
  └── ember-cli-typescript@5.2.1 deduped

ember-cli-typescript-blueprints was not installed automatically in the newly create project, but adding it by hand doesn't change the result.

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

I'm using defaults just after the creation of a new project with ember-cli 5.1

### What are instructions we can follow to reproduce the issue?
<pre>
ember new sample --typescript; cd ./sample
ember g component comp1
ember s
</pre>

Ember is not able to build the project with this error:

<pre>
tests/integration/components/comp1-test.ts:15:21 - error TS2339: Property 'element' does not exist on type 'TestContext'.

15     assert.dom(this.element).hasText('');
                       ~~~~~~~

tests/integration/components/comp1-test.ts:24:21 - error TS2339: Property 'element' does not exist on type 'TestContext'.

24     assert.dom(this.element).hasText('template block text');
                       ~~~~~~~

Typechecking failed
</pre>

**Comment by chriskrycho** [comment]
Thanks for the report. Please re-open this against the ember-source repo, as that is where the blueprints live, now!

**Comment by Polve** [comment]
blueprints of current ember-cli version (5.3.0) seems correct now, thanks
