### ISSUE TITLE
Issue when building ember app with exports from GTS file into TS file

### ISSUE THREAD

**Issue by Techn1x** [typed-ember/ember-cli-typescript#1566]
### Please paste the output of `ember -v` here

ember-cli: 5.0.0
node: 18.16.0
os: darwin arm64

### Please paste the output of `tsc -v` here

Version 5.1.6

and `glint --version`
1.1.0

### Please paste the version of `ember-cli-typescript` and `ember-cli-typescript-blueprints` here

devDependencies:
ember-cli-typescript 5.2.1

### Please paste your `tsconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

{
  "extends": "@tsconfig/ember/tsconfig.json",
  "compilerOptions": {
    "experimentalDecorators": true,
    "allowJs": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "noEmitOnError": false,
    "allowSyntheticDefaultImports": true,
    "noUncheckedIndexedAccess": false,
    "noPropertyAccessFromIndexSignature": false,
    "paths": {
      "my-app/tests/*": ["tests/*"],
      "my-app/mirage/*": ["mirage/*"],
      "my-app/*": ["app/*"],
      "*": ["types/*"],
      "ember-cli-flash/*": ["node_modules/ember-cli-flash"]
    }
  },
  "glint": {
    "environment": ["ember-loose", "ember-template-imports"]
  },
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*",
    "mirage/**/*",
    "node_modules/@gavant/glint-template-types/types/ember-concurrency/perform.d.ts",
    "node_modules/@gavant/glint-template-types/types/ember-truth-helpers/*.d.ts",
    "node_modules/@gavant/glint-template-types/types/ember-modal-dialog/modal-dialog.d.ts",
    "node_modules/@gavant/glint-template-types/types/@fortawesome/ember-fontawesome/fa-icon.d.ts"
  ]
}

  
</pre></details>

### What are instructions we can follow to reproduce the issue?

Setup an ember app with glint. Try to export something from the GTS file and import it in a TS file. It'll work for types etc. but it'll produce a standard types error during build `pnpm ember build` for example, saying it can't find the type exported from the gts file - eg
```
app/components/tables/progress-table/component.ts:54:27 - error TS2307: Cannot find module 'my-app/components/alert' or its corresponding type declarations.

54 import { IconClass } from 'my-app/components/alert'
```

### Now about that bug. What did you expect to see?

No errors during build

### What happened instead?

Erros during build

When building types for ember apps with glint, you're supposed to use `glint` rather than `tsc`. However, this addon seems to only use `tsc`
https://github.com/typed-ember/ember-cli-typescript/blob/7a2422e74e49f676b9c61726d914f64706b4c57d/ts/lib/commands/precompile.ts#L28

**Comment by chriskrycho** [comment]
Yep, this is expected behavior (though perhaps surprising for long-time users). I will be pushing updates to the docs in a little indicating that we are putting ember-cli-typescript into maintenance mode, and recommending people directly configure `ember-cli-babel` and `glint` instead of using this package. It will continue to be maintained, but we do not expect to add Glint build integration into this package. Closing this accordingly!

**Comment by Techn1x** [comment]
Can confirm this is resolved once ember-cli-typescript is dropped - thanks!
