### ISSUE TITLE
Models blueprint with only ES6 class (using ES7 decorators)

### ISSUE THREAD

**Issue by championswimmer** [typed-ember/ember-cli-typescript#161]
This works perfectly fine (even if not using ember-cli-typescript) - 

```js
import Model from 'ember-data/model';
import { attr } from 'ember-decorators/data';

export default class User extends Model {
  @attr('string') name
}
```

So why not use this as the default blueprint for Models
`Models.create()` looks more Mixin-ish than the Typescript way

**Comment by chriskrycho** [comment]
@championswimmer good suggestion – it's on our radar, but we (and Ember.js itself) are waiting to push decorators in any kind of standard way until they reach Stage 3 in the TC39 approval process. At that point, both Babel and TypeScript should be implementing the same semantics for decorators, and we'll be able to be reasonably confident that the spec won't shift in serious ways again as it has in the past.

Happily, it looks reasonably likely that'll happen this month! If so, then probably in April or May—once the TS and Babel implementations are updated to match—we'll make exactly this switch.

As an aside: thanks for verifying that that works! I told @pzuraq that I was going to spend some time testing it, but it looks like you've knocked that off my to-do list (and I'm grateful 😅).

I'm tagging this "Deferred" to indicate we *do* plan to do it – just not yet!

**Comment by mike-north** [comment]
moved to https://github.com/typed-ember/ember-cli-typescript-blueprints/issues/5
