### ISSUE TITLE
Cannot find module './config/environment'

### ISSUE THREAD

**Issue by Bouke** [typed-ember/ember-cli-typescript#163]
With a new application, TypeScript cannot find the config;
```
# app/router.ts
import config from './config/environment'
```

To reproduce:
```
ember new ember-ts
cd ember-ts
ember install ember-cli-typescript
mv app/router.js app/router.ts
ember build
```

This gives the following error:
```
app/router.ts(2,20): error TS2307: Cannot find module './config/environment'.
```

**Comment by chriskrycho** [comment]
Rework that to `ember-ts/config/environment`. The path is mapped by Ember CLI under the hood, somewhat annoyingly.

**Comment by Bouke** [comment]
That produces the following error -- still unable to find the type definitions:
```
12:50:54 PM - Starting compilation in watch mode...
app/router.ts(2,20): error TS2307: Cannot find module 'ember-ts/config/environment'.
12:50:59 PM - Compilation complete. Watching for file changes.
```

**Comment by dfreeman** [comment]
I'm not a real expert at dealing with declarations, but a couple observations:
 - I can reproduce this problem with a fresh app even after changing to the absolute import
 - Wrapping the declaration in `declare module 'ember-ts/config/environment { ... }` (and removing the `declare` before `namespace` causes things to resolve correctly
 - One advantage to having `environment.d.ts` _in_ `app` was that the relative `./config/environment` import from the default blueprint worked

**Comment by chriskrycho** [comment]
Ugh, typings and imports and Ember CLI magic do not all get along very well. @dfreeman if you've got time, let's put it back to where it was, and document the fix?
