### ISSUE TITLE
Parsing error: Unexpected character '@' when ember builds

### ISSUE THREAD

**Issue by danr1979** [typed-ember/ember-cli-typescript#174]
Hi.

I am in the process of migrating my ember app to typescript using this add-on and all has gone well so far.  However, when serving my app in development eslint reports lots of:

`Parsing error: Unexpected character '@'`

This warning relates to the decorators that I have used [https://github.com/ember-decorators/ember-decorators](https://github.com/ember-decorators/ember-decorators) as per your recommendation.  Is there any way I can get eslint to recognise them as valid code so I don't get so many linter errors in my build please?

Any help would be appreciated.

Thanks.

**Comment by chriskrycho** [comment]
Hi @danr1979 – note that this isn't at all TS issue, but an ESLint issue! See [here](https://github.com/babel/babel-eslint) – you should be able to use babel-eslint to make that work.
