### ISSUE TITLE
Support `test-support` and `addon-test-support` code

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/ember-cli-typescript#175]
Addons can expose code that's only available in test builds via `test-support` (which merges into `<app-name>/tests` and `addon-test-support` (which becomes `<addon-name>/test-support`). We should support transpiling from these two directories, as well as generating type declarations for publishing for the stuff in `addon-test-support`.

**Comment by chriskrycho** [comment]
I *think* we may have regressed on this with the v2 release. Doing some further investigation now.
