### ISSUE TITLE
Fix support for objects with mixins

### ISSUE THREAD

**Issue by perlun** [typed-ember/ember-cli-typescript#177]
This issue exists to track the current problem we have with `Ember.Route.extend` usage, _with_ mixins. It's basically impossible to get these working with Ember & TypeScript at the moment; [this gist](https://gist.github.com/perlun/367b75cf74f3617886377764fc469a8c) _tries_ but fails.

We should look into the underlying problem; it's likely to be more of a typings issue than an issue with the preprocessor itself. I hope it's fine to keep this issue here anyway, to track this.

**Comment by chriskrycho** [comment]
@perlun Thanks for the report!

**Comment by perlun** [comment]
@jamesarosen Thanks, updated title to reflect this.

**Comment by perlun** [comment]
@jamesarosen @chriskrycho Here is an example where it seemingly works correctly: https://github.com/CenterForOpenScience/ember-osf-web/blob/develop/app/application/route.ts#L7

(thanks to @bitwolfe for that one! 👍)

**Comment by mike-north** [comment]
We need to check to see if his problem is still present with TS 2.8 + `@types/ember ~3.0.0`.

**Comment by chriskrycho** [comment]
Worth note: TS 3.0 seems to have fixed a number of underlying bugs in this space; updating our app to 3.0.3 made quite a few mixin-using things typecheck which previously hadn’t.

**Comment by mike-north** [comment]
As no currently-breaking cases have been reported over the past 9 days, I'm closing this issue.
