### ISSUE TITLE
Typing an EmberArray

### ISSUE THREAD

**Issue by alexlafroscia** [typed-ember/ember-cli-typescript#179]
I have a class with a property that is an `EmberArray` of `strings`. I'm trying to do something like this to annotate the types correctly.

```typescript
import EmberArray, { A } from '@ember/array';

class StateMachine extends EmberObject {
  transitions: EmberArray<string> = A();
}
```

but I get the following error:

> Cannot find name 'EmberArray'

I'm pretty new at TypeScript so I'm not sure how to diagnose this from here. Do you have any ideas?

**Comment by alexlafroscia** [comment]
Interestingly, if I change it to this

```typescript
import Ember from 'ember';
import EmberArray, { A } from '@ember/array';

class StateMachine extends EmberObject {
  transitions: Ember.Array<string> = A();
}
```

I later on get an error when trying to do `this.transitions.pushObject()` because

> Property `pushObject` does not exist on type `Array<string>`

which is true, but `transitions` is not an `Array<string>`, it is an `EmberArray<string>` which _does_ have a `pushObject` method.

**Comment by dwickern** [comment]
You found a bug in the typings: `EmberArray` the _value_ is being exported but not `EmberArray` the _type_. It's a common typescript gotcha.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember/index.d.ts#L3411
```ts
declare module '@ember/array' {
    import Ember from 'ember';
    type EmberArray<T> = Ember.Array<T>; // this line needs to be added
    const EmberArray: typeof Ember.Array;
    export default EmberArray;
}
```

I can spot a few other types in there which need the same fix. If you could open a PR that would be awesome, or I'll get to it tonight

**Comment by alexlafroscia** [comment]
I see, thanks. I'll see if I can make that PR to update the type definitions. Thanks for the quick turn-around on the help here!

**Comment by chriskrycho** [comment]
@alexlafroscia thanks for doing that typing work – does https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24702 resolve this for you?

**Comment by alexlafroscia** [comment]
Ahh, yup! Sorry, forgot about this original issue.
