### ISSUE TITLE
super() methods don't accept arguments

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-cli-typescript#182]
`super()` methods in constructor (or component lifecycle methods) don't accept arguments. Though, as of `ember@3.1` the constructor for components need the `...arguments` spread to be passed.

As @chriskrycho mentioned in slack, it happens to be this line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/81d0e4984d4b5e10668020eacd4b9a4542c5c837/types/ember/index.d.ts#L69-L80

**Comment by chriskrycho** [comment]
Thanks for filing the issue! Wanted to note that I edited your comment *just* to point to the specific current hash so that it will remain a useful link even as the types change under it.

**Comment by jamescdavis** [comment]
Though, note, that there's just a single constructor argument (the initial properties object).

After that PR's merged try:
```
constructor(properties: object) {
    super(properties);
}
```
You should really do this for anything that extends `@ember/object` (so pretty much everything) and overrides the constructor.

**Comment by jamescdavis** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24997 has been merged and released as `@types/ember 2.8.20`
