### ISSUE TITLE
Regarding Registries

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-cli-typescript#183]
I do consider Registries (ModelRegistry, ServiceRegistry, etc.) as meta information as an addition to the actual code but to make the DX more enjoying. When running a blueprint (e.g. `ember g model my-model`) the generated code contains the registry at the end of the file.

It might be a matter of taste, but what I did was to create a file `types/<my-app>/models.d.ts` which only contains the registry for all my models, removing that part of the actual model file itself. A sample for that file looks like this:

```ts
// types/<my-app>/models.d.ts
import MyModel from 'my-app/models/MyModel';
import MyOtherModel from 'my-app/models/MyOtherModel';

declare module 'ember-data' {
	interface ModelRegistry {
		'my-model': MyModel,
		'my-other-model': MyOtherModel,
		// ...
	}
}
```

To me, this is way more clean, since app code and meta is separated. Blueprints (do they support logic?) could be changed to create files separated that way.

Downside would be, that not using a generator would probably miss that information. However, that is the same, when migrating js to ts files manually.

**Comment by chriskrycho** [comment]
Concur; in fact, this is a [duplicate](https://github.com/typed-ember/ember-cli-typescript/issues/122) of something we're already planning to do! (Closing in favor of the original issue there!)

**Comment by gossi** [comment]
Haha, I'm so bad at my "research". Lovely to see the same genius at work 😍
