### ISSUE TITLE
Different flavors of blueprints

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-cli-typescript#184]
I do think, the blueprints for class generation can come in different flavors, depending on what might be additionally installed or wished by the developer.

E.g. with ember-decorators writing classes in TS is blessing and very much enjoyable. Different blueprints can be used, when the ember-decorators is listed in `package.json` to support the expected way of writing ember code (just found #161 afterwards, upsi).

Similarly (don't know if it must be done in this addon or if ember-cli provides the correct path) is the destination of created files (see MU). 

See also #183 (which cab be considered as another flavor).

**Comment by mike-north** [comment]
Blueprint-related issues are being tracked [here]() now. I've moved your issue to https://github.com/typed-ember/ember-cli-typescript-blueprints/issues/6 . Closing this copy.
