### ISSUE TITLE
Support file renames / additions / deletions in --watch mode

### ISSUE THREAD

**Issue by Bouke** [typed-ember/ember-cli-typescript#186]
Building on Windows is... well slow. So we mostly run `ember build` with the `--watch` option. However in this mode, file renames / additions / deletions of typescript files are not being picked up, and we need to restart `ember build`. It would be very nice if this package would handle situations like these.

**Comment by chriskrycho** [comment]
@Bouke totally agreed (though in my experience it’s more that *sometimes* they’re picked up, which is even more frustrating!). I’m curious: can you try the WIP branch we have for invoking TS’s watch mode more carefully (PR #172) and see if it handles renames better? I think it *may* but I haven’t had looked at that specifically yet. Either way, can you please report the results on #172? That’d be super helpful.

**Comment by dfreeman** [comment]
Additions, and the adding part of renames, should work out of the box with #172, but `tsc --watch` [doesn't currently clean up emitted files when the source is removed](https://github.com/Microsoft/TypeScript/issues/16057), unfortunately. Once #172 lands, we can probably layer on our own handling for that.

**Comment by chriskrycho** [comment]
I believe this was largely resolved by ember-cli-typescript v2 (many years ago now!), and while there are intermittent cache issues with Broccoli, they are are outside the remit of this project to resolve *and* we recommend people switch to using `ember-cli-babel` in apps and Rollup plugins in add-ons for building and `glint` for type checking regardless. Closing as “done”!
