### ISSUE TITLE
Crashing test server

### ISSUE THREAD

**Issue by alexlafroscia** [typed-ember/ember-cli-typescript#201]
I started a new Ember addon today and decided to add `ember-cli-typescript` to is. I decided to kick the tires on the latest beta release, too. However, I keep getting this weird error where the Testem server just crashes while I'm working with my tests. It seems to be related to using `debugger;` in my tests.

I'm not 100% sure that it's `ember-cli-typescript` but I'm pretty sure it is since I've never seen this before and everything else about this addon is really standard. I've also written an addon with `ember-cli-typescript@1.2.1` and didn't have this issue... Maybe it's due to the new, more aggressive TypeScript compiler settings introduces in the recent beta?

**Comment by chriskrycho** [comment]
I'll test both ways before we cut 1.3.0 on Monday to be sure – haven't seen this, though, running in our app context.

Have you managed a reproduction yet?

**Comment by alexlafroscia** [comment]
It happened to me a number of times in a row while working on the add-on today. I ended up just un-installing `ember-cli-typescript` and the error stopped as well.

**Comment by dfreeman** [comment]
Interesting. I was working on tests in an addon with the latest beta earlier today and didn't have any trouble, though I don't _think_ I've totally updated the `tsconfig` to match our new defaults. Was there any meaningful information in the Testem error message?

**Comment by chriskrycho** [comment]
FWIW, there's no difference compiler-version-wise between the two releases; the typings have been updated, and are likely just catching things they wouldn't have before.

**Comment by alexlafroscia** [comment]
Haven't seen this issue in a while so I'm going to go ahead and close it. I'll follow up if I notice anything weird again.

**Comment by chriskrycho** [comment]
Thanks!
