### ISSUE TITLE
New application blueprints

### ISSUE THREAD

**Issue by Gaurav0** [typed-ember/ember-cli-typescript#203]
Create blueprints just like https://github.com/emberjs/ember-module-unification-blueprint for automatically creating and setting up a new ember application with TypeScript.

Right now, if we follow the instructions on the README, we still end up needing to do lots of work to finish setting up our ember app for TypeScript. Initially created files are still .js, and converting them to .ts still results in many TypeScript errors.

**Comment by chriskrycho** [comment]
Thanks for the issue! One of several things we need to support for MU!

**Comment by Gaurav0** [comment]
@chriskrycho This is also needed if you aren't using MU.

**Comment by chriskrycho** [comment]
Ah, I see what you're getting at. We're currently (tentatively) planning to address this another way – keep your ears peeled.

**Comment by bryanaka** [comment]
@chriskrycho anything I can do to help? I am building out an app using MU and typescript right now, so happy to spike out some effort toward getting blueprints working with MU.

**Comment by chriskrycho** [comment]
@bryanaka let’s track this as an issue on the newly-started [blueprints repository](
https://github.com/typed-ember/ember-cli-typescript-blueprints]! @dfreeman is leading the charge on splitting that out (among other things, to increase cycle times on the build pipeline changes here and blueprints changes there).

With that in view, I’m going to close this issue; would one of you mind opening it anew there?
