### ISSUE TITLE
incremental rebuilds do not include updates to .ts files

### ISSUE THREAD

**Issue by jamesarosen** [typed-ember/ember-cli-typescript#206]
### Environment
node 8.11.1
ember-cli 3.1.4
ember-cli-typescript: 1.3.0
typescript: 2.8.3

```js
// ember-cli-build.js
'use strict'
const EmberApp = require('ember-cli/lib/broccoli/ember-app')
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    hinting: false,
  })
  if (app.env === 'development') {
    app.import('vendor/csp-script-test.js')
  }
  app.import('vendor/google-analytics.js')
  return app.toTree()
}
```

### Problem

When I run `DEBUG=ember-cli-typescript* ember serve`…

 1. if I change an `app/**/*.js` file, ember-cli ✅ sees the change, ✅ rebuilds, ✅ tells the browser to refresh, and ✅ responds with the updated `/assets/myapp.js`.
 2. if I change an `app/**/*.ts` file, it does all of those steps except the last. That is, the page refreshes, but the compiled JavaScript does not reflect my recent changes.
 3. if I change a `.ts` file and then a `.js` file only the `.js` changes are reflected in `myapp.js`.
 4. if I change a `.ts` file and then `touch` the same file, no changes are reflected in `myapp.js`.

I get the following debug output when I change `app/components/my-component.ts` (and when I `touch` it):
```
file changed components/my-component.ts
  ember-cli-typescript:compiler-state broccoliDidStart | broccoli: 1 active nodes | tsc: idle (0 errors) +18s
  ember-cli-typescript:compiler-state broccoliDidEnd | broccoli: 0 active nodes | tsc: idle (0 errors) +0ms
  ember-cli-typescript:compiler-state broccoliDidStart | broccoli: 1 active nodes | tsc: idle (0 errors) +209ms
  ember-cli-typescript:compiler-state broccoliDidEnd | broccoli: 0 active nodes | tsc: idle (0 errors) +0ms
  ember-cli-typescript:compiler-state broccoliDidStart | broccoli: 1 active nodes | tsc: idle (0 errors) +1ms
  ember-cli-typescript:compiler-state broccoliDidEnd | broccoli: 0 active nodes | tsc: idle (0 errors) +0ms
  ember-cli-typescript:compiler-state broccoliDidStart | broccoli: 1 active nodes | tsc: idle (0 errors) +339ms
  ember-cli-typescript:compiler-state broccoliDidEnd | broccoli: 0 active nodes | tsc: idle (0 errors) +0ms
```

On `ember-cli-typescript@1.2.1`, I get the same behavior with slightly different logging output:
```
file changed components/my-component.ts
  ember-cli-typescript:compiler broccoli detected a file change +11s
  ember-cli-typescript:compiler waiting for tsc output {} +0ms
  ember-cli-typescript:autoresolve no tsc rebuild; autoresolving... +32s
  ember-cli-typescript:compiler tsc build complete {} +505ms
  ember-cli-typescript:compiler waiting for tsc output { mirage: 'app/mirage' } +212ms
  ember-cli-typescript:compiler tsc build complete { mirage: 'app/mirage' } +1ms
  ember-cli-typescript:compiler waiting for tsc output { './app': 'app' } +1ms
  ember-cli-typescript:compiler tsc build complete { './app': 'app' } +0ms
  ember-cli-typescript:compiler waiting for tsc output { tests: 'tests' } +604ms
  ember-cli-typescript:compiler tsc build complete { tests: 'tests' } +0ms
```

Per #158, I've tried VSCode, vi, and `touch` to modify the file.

Possibly related to #125, #158, #204

**Comment by pixelhandler** [comment]
@jamesarosen I had a similar issue with `ember b -w` reported in #204 I think we may be looking at the same root cause.

**Comment by jamesarosen** [comment]
1.3.0-beta.4 acts the same as 1.3.0 for me. (I assume you didn't mean 1.0.3-beta.4, since no such version exists.)

**Comment by jamesarosen** [comment]
Good intuition! The real path of my app is `/Users/jamesrosen/.devly/library/repos/myapp/` The `.devly/library/` bit is a required path for one of our in-house tools.

**Comment by jamesarosen** [comment]
Ok. I'm able to move the project directory, so this is resolved for me.

If it's not easy to start applying that regex _after_ the project root dir, could we add a warning if the project root itself matches that regex? I'm just trying to keep other people from falling into this pit.

**Comment by dfreeman** [comment]
Glad that worked! Definitely agreed that this is a gotcha we should avoid—I think we ought to be able to do a better job just ignoring things after the project root.
