### ISSUE TITLE
Inverse-reflexive Ember Data relationships not working

### ISSUE THREAD

**Issue by backspace** [typed-ember/ember-cli-typescript#213]
Hello! I mentioned this in the Ember Slack and @chriskrycho recommended opening an issue, so here I am.

I’m getting acquainted with Typescript by converting an [existing application](https://github.com/backspace/prison-rideshare-ui/) for a rides-to-prison project. A `Ride` is one of the main models, so I’m coming to it near the end of my conversions, but I’ve run into some trouble with the tree-like relationship because a ride can be [“combined” with another](https://github.com/backspace/prison-rideshare-ui/compare/typescript-ride?expand=1#diff-a3812e788a36d99cef2ecd3e86a55034L17) when visitors are going to the same prison at the same time:

```
export default class Ride extends DS.Model.extend({
  … 
  combinedWith: DS.belongsTo('ride', {inverse: 'children'}),
  children: DS.hasMany('ride', {inverse: 'combinedWith'}),
  …
```

The relationship options are highlighted with errors; here are the errors for the first one:

```
Argument of type '{ inverse: "children"; }' is not assignable to parameter of type '(RelationshipOptions<Ride> & Async) | undefined'.
  Type '{ inverse: "children"; }' is not assignable to type 'RelationshipOptions<Ride> & Async'.
    Type '{ inverse: "children"; }' is not assignable to type 'RelationshipOptions<Ride>'.
      Types of property 'inverse' are incompatible.
        Type '"children"' is not assignable to type '"allPassengers" | null | undefined'.
```

The `allPassengers` reference at the bottom is a computed property that depends on `children`, but even if I delete `allPassengers`, the error remains, so it seems to me not to be the problem.

Let me know if you need anything else! I’m grateful for the work you all have done on this.

**Comment by chriskrycho** [comment]
Closing this since the recommended solution (using decorators) has been a stable part of the Ember and Ember Data APIs for several years now.
