### ISSUE TITLE
Need option to broaden exclusions from TS watcher

### ISSUE THREAD

**Issue by lupestro** [typed-ember/ember-cli-typescript#216]
The CONCAT_STATS=true flag of broccoli-concat is used to collect the measured sizes of various pieces a built project and is instrumental in measuring svelting. It puts files in a `concat-stats-for` subdirectory, and the names of the files include directories with names like `2-vendor.js` and `3-vendor.css`.

With typescript in play, this hangs the build - perhaps it is being misled by directories that are named like JS and CSS files. Hand-editing the `concat-stats-for` directory into the list of exclusions in `lib/utilities/compile.js` enables the build to complete without an issue.

This is probably not the only situation where it would be desirable to exclude a directory from being watched by the TS build. An option to extend the list of exclusions would permit users encountering build issues to keep directories like this out of harm's way.

**Comment by chriskrycho** [comment]
@lupestro can you see whether this is still an issue in 1.5, and also whether it's an issue in the v2 beta?

**Comment by lupestro** [comment]
I didn’t get as far today as I’d hoped. The project and our addons for it are using ec-typescript 1.3.1 against typescript 2.9.1 - pretty far back. Things are getting busy to turn the sprint tomorrow night so my team can continue while I’m on holiday - it may be after Thanksgiving before I have experimental results with 1.5 for you.

**Comment by lupestro** [comment]
Even with the ec-typescript 1.3.1, with the in-repo addons gone, this builds fine with concat_stats turned on (just tried it), so results with 1.5 won’t be definitive. More news later, if you’re still interested.

**Comment by chriskrycho** [comment]
Going to close this as (1) it's long out of date and (2) we now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tac` directly on their projects.
