### ISSUE TITLE
Missing handlebars type definition after installation

### ISSUE THREAD

**Issue by alexlafroscia** [typed-ember/ember-cli-typescript#220]
I just installed the latest release of `ember-cli-typescript` in my application and right off the bat am getting this warning:

> node_modules/@types/ember/index.d.ts(14,23): error TS2688: Cannot find type definition file for 'handlebars'.

Is this something that should be installed by default with the other type definitions?

**Comment by dfreeman** [comment]
Something odd happened with the most recent published version of `@types/ember`, and we haven't figured out how to deal with it yet, unfortunately. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26111#issuecomment-393590233

**Comment by dfreeman** [comment]
For anyone who does come across this (it also came up in #217), installing `@types/handlebars` by hand should be fine as a temporary workaround.

**Comment by alexlafroscia** [comment]
Yup, that's what I ended up doing 👍 thanks for the link to the issue to follow along with!

**Comment by dfreeman** [comment]
This should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26392
