### ISSUE TITLE
service generator blueprint is not overriding the default ember-cli in ember 3.2.0

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#233]
In `ember-cli 3.1.4` `ember g service test` creates a `.ts` file with all the lovely shiny stuff in it.

In `ember-cli 3.2.0` I generated a new one with `ember g service test` and got:

```
// addon/test/service.js
import Service from '@ember/service';

export default class Test1Service extends Service {
}
```

**Comment by BryanCrotaz** [comment]
Logging this in ember-cli too - not sure which side of the fence it falls

**Comment by BryanCrotaz** [comment]
See https://github.com/ember-cli/ember-cli/issues/7900

**Comment by jamescdavis** [comment]
It was actually `ember-decorators`' blueprint that was overriding `ember-cli-typescript`. This should be fixed in the next release of `ember-cli-typescript`. Recommend closing https://github.com/ember-cli/ember-cli/issues/7900.

**Comment by BryanCrotaz** [comment]
Well sleuthed. 

How does blueprint priority work?
