### ISSUE TITLE
[discussion] How should we handle templates?

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#242]
Currently, importing a template (i.e., in an addon's component) includes a 

##### lib/my-addon/addon/components/x-foo.ts
```ts
// @ts-ignore: Ignore import of compiled template
import layout from '../templates/components/x-foo';
```
to get around the issue of typescript being unable to resolve the module. Since we're already maintaining a lot of bookkeeping for addons (in particular, `tsconfig.json` paths/includes for in-repo addons/engines), have we considered 

##### lib/my-addon/addon/components/x-foo.ts
```ts
import layout from 'my-addon/templates/components/x-foo';
```
along with
##### (A) types/my-addon.d.ts
```ts
declare module 'my-addon/templates/*' {
  import { TemplateFactory } from "htmlbars-inline-precompile";
  export default TemplateFactory
}
```
or 

##### (B) types/my-addon.d.ts
```ts
declare module 'my-addon/templates/*' {
  export default any
}
```

or 

##### (C) types/my-addon.d.ts
```ts
declare module 'my-addon/templates/*' {
  export default any
}
```

**Comment by chriskrycho** [comment]
Relevant: #192.
