### ISSUE TITLE
component attrs don't typecheck

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#243]
The below code works at runtime but fails to type check at compile time
```ts
export default class MyComponent extends Component {
  click() {
    this.onChange(); // onChange isn't recognised as a valid field
  }
}

{{my-component onChange=(action doSomething) }}
```

Adding a field to keep TS happy breaks Ember 3.1
```ts
export default class MyComponent extends Component {
  onChange: any = null;

  click() {
    this.onChange(); // onChange is null
  }
}

{{my-component onChange=(action doSomething) }}
```

What's the correct way to go about this?

**Comment by chriskrycho** [comment]
Don't set it to `null` explicitly; see the discussion [here](https://github.com/typed-ember/ember-cli-typescript/issues/151#issuecomment-368029737) for some details. By doing `onChange: any = null` instead of just `onChange: any` (or better, `onChange: Function`), you're stomping any value passed in.

```ts
export default class MyComponent extends Component {
  onChange: Function;

  click() {
    this.onChange(); // onChange is null
  }
}
```

**Comment by BryanCrotaz** [comment]
Then you’ll get a TS warning saying the field isn’t assigned a value by the constructor.

**Comment by chriskrycho** [comment]
Right; in that case you'll need to use the [definite assignment assertion operator](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization) to tell it "no, this is definitely assigned."

**Comment by chriskrycho** [comment]
You’re welcome!
