### ISSUE TITLE
[@types/ember enhancement] - Cleanup around Ember.Object.{extend, reopen}

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#291]
### Which package(s) does this enhancement pertain to?
  - [x] @types/ember

### Please write a user story for this feature

> As **a maintainer of the ember type information**, I want **to remove some hacks around Ember.Object.extend that were necessary in TS 2.x** so that **the types are more approachable to existing and future contributors**.

---

**related conversation:** https://discordapp.com/channels/480462759797063690/484421406659182603/489476577529167875
**related code change:**
https://github.com/mike-north/DefinitelyTyped/commit/690bfedacba421ea461b2c02ffc56d65587c5fd0

The main part of this cleanup effort aims to do two things

## 1. Ensure that `Ember.Object.extend` and `Ember.Object.reopen` return a type that accurately represents what these functions actually do.

Conceptually, these functions essentially return the union of their input
```ts
class A { foo: 'hello' }
const B = A.extend({
   foo: 65
});
let b = new B();
b; // string | number
```
In the above example, we're lying about the type of b. It will definitely be a number because we override the original property when defining B.

In terms of implementation the way to do this is to define a new utility type that's **the union of B and anything on A that is not present on B**
```
B ∪ (A - B)
```

The TS implementation looks like
```ts
type Mix<A, B> = B & Pick<A, Exclude<keyof A, keyof B>>;
```

Then we can go and update types that currently look like this
```ts
static extend<...>(
    this: Statics & EmberClassConstructor<Instance>,
    arg1: MixinOrLiteral<T1, B1> & ThisType<Instance & T1>,
    arg2: MixinOrLiteral<T2, B2> & ThisType<Instance & T1 & T2>
): Objectify<Statics> & EmberClassConstructor<Instance & T1 & T2>;
```
to using `Mix<A,B>` instead of `A & B`
```ts
static extend<...>(
    this: Statics & EmberClassConstructor<Instance>,
    arg1: MixinOrLiteral<T1, B1> & ThisType<Instance & T1>,
    arg2: MixinOrLiteral<T2, B2> & ThisType<Instance & Mix<T1, T2>>
): Objectify<Statics> & EmberClassConstructor<Instance & Mix<T1, T2>>;
```
There are many reasonable test cases that currently fail, and this change would allow them to pass, and provide us with more maintainable types, and more accurate and complete type safety across some of the most commonly used areas of Ember (i.e., `get()` and `set()`)

## 2. Remove a workaround that was necessary in the TS2.x release series to properly handle things like `_super` and statics through an ineritance chain in a typed ember addon

related issue: https://github.com/typed-ember/ember-typings/pull/29)

There's a difficult-to-test (in the way we typically test ambient types) but reproducable issue involving extending from types through an addon in pre-3.0 versions of TypeScript.

##### Example:
My app uses `ember-resize`, which provides its own types that refer to `@types/ember`.

You can then try things like
```ts
import ResizeService from 'ember-resize/services/resize';

const Another = ResizeService.extend({});
class Another2 extends ResizeService.extend({}) {}
class Another3 extends ResizeService {}

const a1 = Another.create();
const a2 = new Another();
const a3 = Another2.create();
const a4 = new Another2();
const a5 = Another3.create();
const a6 = new Another3();
```
and you'll get an error on each of the `a1` - `a3` declarations. The message will have something to do with static properties like `prototype`. Tracking down the root cause for this reveals that the conflict/collsion is around the static properties of each class in the inheritance chain.

The workaround @dwickern and @dfreeman figured out was to make the statics `Readonly<T>` in `.extend`'s return type.

In TS 3 this is no longer necesary, and the types become more flexible by removing this workaround.

**Comment by dwickern** [comment]
> ```ts
> class A { foo: 'hello' }
> const B = A.extend({
>    foo: 65
> });
> let b = new B();
> b; // string | number
> ```

Should we allow this? The equivalent code in regular typescript doesn't compile.
```ts
class A { foo: 'hello' }
class B extends A {
    foo: 65 // Property 'foo' in type 'B' is not assignable to the same property in base type 'A'.
}
```

You could use a type annotation if it was really your intent.
```ts
class A { foo: string | number = 'hello' }
```

**Comment by mike-north** [comment]
> Should we allow this? The equivalent code in regular typescript doesn't compile.

No, but that's the current behavior. it should be 
```ts
b; // number
```

**Comment by chriskrycho** [comment]
This sat for a loooong time, and since as part of [Ember RFC 0800](https://rfcs.emberjs.com/id/0800-ts-adoption-plan/) we decided to *drop* support for complex type inference in `.extend()` in favor of telling people to use native classes (which actually *work*), I'm closing this. It's been a long time coming!
