### ISSUE TITLE
Ember smoke test should be cleaned up

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#316]
Originally posted by @BryanCrotaz https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29119

---

Comes out of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29079

The smoke test that checks module stuff is imported into Ember global requires a clean up.

If it is a pure smoke test that the correct exports have been declared, then clearly it doesn't need 100% code coverage of the module code. So a single call into each class or function would be enough to check that the export is present. At present some calls are made with multiple overload patterns, and some are not made at all. We should either test the minimum or the maximum - as this is a smoke test it should just test the minimum, otherwise other contributors will be tempted (as I was in my first review) to fill the gaps.

Checking that the correct export mapping has been made should be possible by checking the type of the new object for example.

Some/most test calls use $ExpectType to confirm the result type. But many don't and if we're going to do it at all we should do it everywhere.

Tasks:

  - [ ] clean up unnecessary overloads
  - [ ] add $ExpectType to every call

**Comment by BryanCrotaz** [comment]
#confused
Why is this relevant to e-c-typescript? Is there another smoke test here?

**Comment by mike-north** [comment]
@BryanCrotaz we track issues relating to `@types/ember` here, because (among other reasons) we have no ability to assign/label/organize issues on DefinitelyTyped

**Comment by BryanCrotaz** [comment]
I see your pain...

is there an equivalent of ExpectType that can assert that a call does not return `any`?

**Comment by mike-north** [comment]
> is there an equivalent of ExpectType that can assert that a call does not return any?

Not that I'm aware of. `any` is type-equivalent to anything, so an assignment inherently can't catch this.

**Comment by BryanCrotaz** [comment]
Am I right in thinking that TS is all about duck typing, so it's impossible to say what the declared return type was, only to be able to ask questions about the object you got?

**Comment by mike-north** [comment]
TS can often infer a return type, or you can explicitly provide one. For example
```ts
const foo = () => 'hello';
function bar(): string {
 // something
}

ReturnType<typeof foo> // string
ReturnType<typeof bar> // string
``
these functions both have a return type of `string`. Depending on your `tsconfig.json`, you can allow a high or low degree of flexibility around these kinds of things. Ambient type declarations like `@types/ember` generally are written with a high level of strictness, but consuming apps may be far more lax.

**Comment by mike-north** [comment]
We have three options

1. We can write a test based on the question of type equivalence (i.e., "Is the return type of this function __assignable to__ the following type"). This, of course, allows for return types of `any` that are assignable to anything.

2. We can write a test that asserts an exact string match on the return type of something ( `// $ExpectType` ). This can be prohibitively brittle, in that some of our types are very complicated in fully-expanded form.

3. We can assert that an error is thrown `// $ExpectError`. This is the most effective way to ensure that something isn't an `any` (i.e., we want a value to be a `string`, the compiler should error if we attempt to treat it like a `number`).

**Comment by BryanCrotaz** [comment]
> We can assert that an error is thrown

sounds like the best way. Does this fit into smoke tests, or should this be in the detailed test?

**Comment by BryanCrotaz** [comment]
We could even define a const for testing this
```
type NotAny = { ____thisIsCompatibleOnlyWithAny: true }; //defined globally somewhere
let test:NotAny = myObj.doSomethingThatShouldReturnComplexThing(); // $ExpectError
```

**Comment by mike-north** [comment]
Yeah this is one of the strategies we already apply quite broadly in the deeper tests. There's a cleaner way to do it though

```ts
type NotAny = { ____thisIsCompatibleOnlyWithAny: true }; //defined globally somewhere


const myObj = {
    doSomethingThatShouldReturnComplexThing() { return [1, 2, 3]; }
}

myObj.doSomethingThatShouldReturnComplexThing() as NotAny; // $ExpectError
```
https://www.typescriptlang.org/play/#src=type%20NotAny%20%3D%20%7B%20____thisIsCompatibleOnlyWithAny%3A%20true%20%7D%3B%20%2F%2Fdefined%20globally%20somewhere%0D%0A%0D%0A%0D%0Aconst%20myObj%20%3D%20%7B%0D%0A%20%20%20%20doSomethingThatShouldReturnComplexThing()%20%7B%20return%20%5B1%2C%202%2C%203%5D%3B%20%7D%0D%0A%7D%0D%0A%0D%0AmyObj.doSomethingThatShouldReturnComplexThing()%20as%20NotAny%3B%20%2F%2F%20%24ExpectError%0D%0A

**Comment by chriskrycho** [comment]
Resolved by using [expect-type](https://www.npmjs.com/package/expect-type) to write *much* more robust type tests in Ember’s own published types.
