### ISSUE TITLE
types/ember-data.d.ts completely overwrites ember-data types

### ISSUE THREAD

**Issue by makepanic** [typed-ember/ember-cli-typescript#321]
Hi,
in a completely new ember project with ember-cli-typescript (`^1.4.3`), none of the ember-data types work.

![20181001-121038](https://user-images.githubusercontent.com/1205444/46283924-3de48780-c576-11e8-9eb9-14398f7e692d.png)

If one removes the `ember-data.d.ts`, all ember-data types work again.

![20181001-121008](https://user-images.githubusercontent.com/1205444/46283983-771cf780-c576-11e8-8758-38708f208a08.png)

Is it ok to remove `ember-data.d.ts` or will this break the `ModelRegistry` feature?

**Comment by mike-north** [comment]
Closing as duplicate of #320
