### ISSUE TITLE
[bug] - typescript blueprints do not respect addon ordering

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#322]
### Please paste the output of `ember -v` here
```
ember-cli: 3.5.0-beta.1
node: 8.11.4
os: darwin x64
```

##### Setup
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember install ember-qunit-decorators
```
##### Repro
Run `ember g component-test x-foo`

### Now about that bug. What did you expect to see?

Because of [the addon order](https://github.com/mike-north/ember-qunit-decorators/blob/2466c0d1fbf7d2b1afed5653c09290b4a99b14de/package.json#L82-L88), I'd expect to see the code generated by `ember-qunit-decorators`.

### What happened instead?
I see the code generated by `ember-cli-typescript-blueprints`

----

This problem is due to the fact that we do not respect addon ordering when inserting `ember-cli-typescript-blueprints` into the discovered addons array

https://github.com/typed-ember/ember-cli-typescript/blob/c0bc3d7460ea929ac18d0e0b2ee8b9218b358c82/ts/addon.js#L30-L32

The code as it currently stands, will result in the `e-cli-ts-blueprints` code generation winning out over all other addons.

We should probably find the index of `ember-cli-typescript` in the array, and splice the blueprints in immediately after it.

**Comment by jamescdavis** [comment]
Here's the reason this is happening: https://github.com/typed-ember/ember-cli-typescript-blueprints/blob/master/package.json#L75
Both are asking to run after the other and `ember-cli-typescript-blueprints` is winning (not sure how ember-cli decides this, though).

**Comment by mike-north** [comment]
@jamescdavis to be clear -- `after` does not mean `immediately after`. There's no conflict here -- both addons run _at some point_ after e-cli-decorators has run

**Comment by jamescdavis** [comment]
I originally misread and thought `ember-cli-typescript-blueprints` was saying after `ember-qunit-decorators`, but it's just saying after `ember-decorators`. Sorry to add to the confusion. I still think something weird is going on with the way the addons order specifications are interacting.
