### ISSUE TITLE
TODO: let's make a roadmap!

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#331]
1. Let's make a lightweight roadmap doc so we have an easy place to point people when they are curious what's up, what blockers are, etc. Thoughts on what all should go in it?
2. Where should we put it? The README is bonkers-full already, but my experience with GitHub Wikis is that people *don't see them*; we'll at least need to link it from the README of course.
3. I… think that's it, actually? But my brain is [still shot][burnout], so maybe I missed something?

[burnout]: https://www.chriskrycho.com/burnout

**Comment by gossi** [comment]
Github has milestones ☝️

**Comment by chriskrycho** [comment]
Well, this was a great idea that we didn't really do. 😂 Insofar as folks are curious who stumble across this issue 5 years later, there *is* a roadmap for TS as part of Polaris, [here](https://github.com/orgs/emberjs/projects/9).
