### ISSUE TITLE
Computed property decorators type issues

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#335]
### Which package(s) does this problem pertain to?
  - [x] @types/ember

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember install ember-decorators
```

##### Reproduction Case

Add a new service in `app/services/foo.ts`:

```typescript
import Service from '@ember/service';
import { computed } from '@ember-decorators/object';
import { filter, map } from '@ember-decorators/object/computed';

export default class Foo extends Service {
  array: string[] = [];

  @filter('array')
  path(_, index, array) {
    return index < array.length - 1;
  }

  @computed('path.[]')
  pathString(): string {
    return this.get('path').map(encodeURIComponent).join('/');
  }

  @map('path')
  encoded(element, index) {
    return this.path.slice(0, index + 1).map(encodeURIComponent).join('/');
  }
}

declare module '@ember/service' {
  interface Registry {
    foo: Foo;
  }
}
```

Running `ember server` gives:

```
app/services/foo.ts(9,8): error TS7006: Parameter '_' implicitly has an 'any' type.
app/services/foo.ts(9,11): error TS7006: Parameter 'index' implicitly has an 'any' type.
app/services/foo.ts(9,18): error TS7006: Parameter 'array' implicitly has an 'any' type.
app/services/foo.ts(15,29): error TS2339: Property 'map' does not exist on type 'UnwrapComputedPropertyGetter<this["path"]>'.
app/services/foo.ts(19,11): error TS7006: Parameter 'index' implicitly has an 'any' type.
app/services/foo.ts(20,22): error TS2339: Property 'slice' does not exist on type '(_: any, index: any, array: any) => boolean'.
```

I'm not sure I fully understand how TypeScript with ember-decorators work, but this seems very wrong.

1) Why are `filter`'s arguments "any"? Filter [does have a type definition](https://ember-decorators.github.io/ember-decorators/latest/docs/api/modules/@ember-decorators/object/computed#filter) - why doesn't it "infer" them somehow?

2) Why does neither `this.get('path')`, nor `this.path` return the correct type (knowing that this is a computed property) - the former returns a `UnwrapComputedPropertyGetter<this["path"]>` and the latter - `(_: any, index: any, array: any) => boolean`.

The second one is the bigger issue - I'm not even sure *how* to make this compile.

**Comment by chriskrycho** [comment]
Thanks for the report! Can you add what versions of each of the following you have?

- `typescript`
- `@types/ember`

**Comment by boris-petrov** [comment]
Thank you for the support! `typescript` is version `3.1.1`, `@types/ember` is at `3.0.24`. Yes, both are latest right now. :)

**Comment by mike-north** [comment]
A lot of this type info is coming from `ember-decorators` JSDoc comments -- the story around using TS types in JSDoc is pretty good, but I think the common path to take is to provide very "loose" information (i.e., good for doc purposes, not nearly strong enough for type-checking purposes)

**Comment by dwickern** [comment]
To answer both your questions, it's because Typescript has very limited support for decorators. A decorator will never change the type of the decoratee.

You can read https://github.com/Microsoft/TypeScript/issues/8250#issuecomment-218831134 for an explanation and subscribe to https://github.com/Microsoft/TypeScript/issues/4881 for updates. I hope to see some progress here as the decorators proposal moves along.

For now I'd recommend sticking to `@computed` which should always type-check correctly.

**Comment by boris-petrov** [comment]
I don't understand - this code:

```typescript
import Service from '@ember/service';
import { computed } from '@ember/object';
import { filter, map } from '@ember/object/computed';

export default class Foo extends Service.extend({
  path: filter('array', function(this: Foo, _, index, array) {
    return index < array.length - 1;
  }),

  pathString: computed('path.[]', function(this: Foo) {
    return this.get('path').map(encodeURIComponent).join('/');
  }),

  encoded: map('path', function(this: Foo, element, index) {
    return this.path.slice(0, index + 1).map(encodeURIComponent).join('/');
  }),
}) {
  array: string[] = [];
}
```

Which is the "official" way of doing this without decorators also does not compile (it gives a `'Foo' is referenced directly or indirectly in its own base expression.` which is actually correct). Am I to understand that currently there is *no way* to make this code compile cleanly? Sticking to `@computed` doesn't work for us as we have thousands of lines of code which use all kinds of computed properties. :) So the only solution is `// @ts-ignore`?
