### ISSUE TITLE
Wrong type definition for ComputedProperty

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#336]
### Which package(s) does this problem pertain to?
  - [x] @types/ember

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
```

##### Reproduction Case

Create a file in `app/utils/bar.ts`:

```typescript
import ComputedProperty from '@ember/object/computed';

export default class Bar extends ComputedProperty<any> {
  constructor() {
    super(function(this: any, key: string) {
    });
  }
}
```

Running `ember server` causes:

```
app/utils/bar.ts(5,5): error TS2554: Expected 0 arguments, but got 1.
```

I think this is wrong. We're using this right now and it works so the type definition here is wrong - the super constructor does accept a function as an argument.

**Comment by chriskrycho** [comment]
Someone else can correct me if I'm wrong, but I don't believe `ComputedProperty` is public API *for extension* like this. 🤔

**Comment by mike-north** [comment]
I believe you're right @chriskrycho -- @boris-petrov you should try using the methods for creating computed properties that are described in the Ember api docs  -- https://www.emberjs.com/api/ember/3.4/classes/ComputedProperty

**Comment by chriskrycho** [comment]
To elaborate on my earlier comment: because it isn't public API for extending, flying on this behavior is dangerous and likely to break on you at any time. (I advised people to rely on the non-public-API behavior of the `ComputedProperty` type in a *different* way early this year, and, well… it broke in Ember 3.1!)
