### ISSUE TITLE
Move *.d.ts folder out of source folder

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-cli-typescript#34]
I was a bit wondering, when the `config/` folder for `*.d.ts` files popped up under my `/app` (soon to be `/src`) folder. I would consider `*.d.ts` files as metadata to my project and I think the current default location is wrong. My goto folder for these files would be `/config/typings`. What do you think?

**Comment by chriskrycho** [comment]
I'll definitely think about that for the general case. 🤔 It makes good sense.

The historical reason it's there (it precedes me!) is that it makes it trivial to map the location correctly when you do `import config from './config/environment'`.

However, we can certainly manage that by way of the `paths` argument in `tsconfig.json`. If you want to write a PR to that effect and test that it works as expected, I'd be 👍 on that approach.
