### ISSUE TITLE
Cannot inject a "mock" service in the tests

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#340]
Hi, I spent 5 full days porting a few of our things from CoffeeScript to TypeScript. It was a huge pain but finally managed to get it working without too many `@ts-ignore`s. :) Thanks for the great project and support, hopefully things will become even smoother in the future!

Now for the issue. We used to do (and still do):

```coffeescript
application.inject('service:some-service', 'store', 'service:mock-store')
```

That is, we mock the "store" service in "some-service" (this is done in the `hooks.beforeEach` block of an acceptance test). This used to work before when we had CoffeeScript only. Now, both services are in TypeScript. In `some-service` I do something like:

```typescript
export default class SomeService extends Service {
  @service store!: Store;
  ..
```

Which works during development but doesn't work in the tests - the service is the original one and not the mocked one. I tried also:

```typescript
export default class SomeService extends Service.extend({
  store: inject('store'),
}) {
  ...
```

But the result is the same. I can't even begin to imagine why converting to TypeScript (and using native classes instead of EmberThing.extend) would break this. Do you have any idea? Is this even for this project or for Ember? Where do I start with debugging this?

**Comment by chriskrycho** [comment]
First thing to check is: (in a branch!) convert that file to plain JavaScript and check whether it has the same problem. I *think* the problem is probably totally unrelated to TS, but we may be able to help you figure out where it *is*.

**Comment by chriskrycho** [comment]
(Whoops, mashed the wrong button; didn't mean to close this!)

**Comment by boris-petrov** [comment]
Hi, thanks for the response! Converting it to a plain JS file also causes the test to fail so yes, this has nothing to do with TypeScript. Probably with using native classes? These both fail:

```javascript
export default class SomeService extends Service {
  @service store;
  ...
```

```javascript
export default class SomeService extends Service.extend({
  store: inject('store'),
}) {
  ...
```

Only this passes:

```javascript
export default class SomeService extends Service.extend({
  store: inject('mock-store'),
}) {
  ...
```

What to do next? Thank you very much for the help!

**Comment by boris-petrov** [comment]
Doing an old-style `export default Service.extend({` causes the test to pass. So the problem is really in the native-class definitions. Any ideas why or should I open an issue in Ember?

**Comment by chriskrycho** [comment]
I think it’s worth opening an issue there, yeah. My guess is that this is related to the way that you can’t do `.extend` on something declared as a `class`.

You also can certainly just tweak how your tests are written, but that’s a bunch of work and may not be desirable right now of course! In our tests we’re using the new style tests and we would simply do `this.owner.register(...)` but not `inject`, as tests which use `setupTest` get access to the normal DI container, and should resolve the right thing automatically if you’ve overridden it.

**Comment by boris-petrov** [comment]
I'll open an issue there, thanks!

Can you show me what you mean by using `this.owner.register(...)`? We also use new-style tests but I'm not sure how you would achieve what I'm trying to do?

**Comment by boris-petrov** [comment]
I've opened the issue [here](https://github.com/emberjs/ember.js/issues/17116). If you check it out, you'll actually see that the problem is in the constructor... for some reason. :) Anyway, until they fix it - can you show me your way with `register`? Thanks!

**Comment by boris-petrov** [comment]
So in the end the constructor should have passed its arguments to "super". Thanks a lot for all the help!
