### ISSUE TITLE
@ember/template should be typed

### ISSUE THREAD

**Issue by HodofHod** [typed-ember/ember-cli-typescript#342]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__string
  - [x] Other

### What are instructions we can follow to reproduce the issue?
```ts
import { htmlSafe, isHTMLSafe } from '@ember/template';

let foo = "bar";
if (!isHTMLSafe(foo)){
  let safeFoo = htmlSafe(foo);
}
```

### Now about that bug. What did you expect to see?
I expected no errors (except maybe an unused variable), and accurate typing for `isHTMLSafe` and `htmlSafe`.

### What happened instead?
TypeScript complains `Cannot find module '@ember/template'.` 

### More information

`htmlSafe` and `isHTMLSafe` used to be in `@ember/string`, and can still in fact be imported from there.  However, the [correct location is in `@ember/template`](https://github.com/ember-cli/ember-modules-codemod/issues/85#issuecomment-386019695), a module that hasn't been typed at all. The typings for these methods are still in `@ember/string`

**Comment by jamescdavis** [comment]
Closed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38571
