### ISSUE TITLE
MutableArray.setObjects does not have to accept EmberArray

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#345]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__array

`MutableArray.setObjects` is defined as:

```typescript
setObjects(objects: EmberArray<T>): this;
```

It works fine when passed a native array so the type definition could be loosened to:

```typescript
setObjects(objects: T[]): this;
```

In the Ember docs it says it accepts an Ember Array but I think this can also be changed.

Or am I mistaken?

**Comment by dwickern** [comment]
👍 

Here's the [source](https://github.com/emberjs/ember.js/blob/c2c8171301d2b1a0c499b4a55009ebf428f40e69/packages/%40ember/-internals/runtime/lib/mixins/array.js#L1451). It can be loosened further to
```ts
setObjects(objects: ReadonlyArray<T>): this;
```

**Comment by chriskrycho** [comment]
This has since been fixed: it [now takes `Enumerable<T>`][current], which correctly accepts native arrays as well.

[current]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d31733647c3751adda12e0c260985734d809a6cb/types/ember__array/mutable.d.ts#L41

**Comment by boris-petrov** [comment]
@chriskrycho - I think you're mistaken. The issue is about `setObjects`, not `pushObjects`, and it still accepts [EmberArray](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d31733647c3751adda12e0c260985734d809a6cb/types/ember__array/mutable.d.ts#L71). Please reopen the issue. :)

**Comment by chriskrycho** [comment]
Ah, you are correct, my apologies! (Thanks for reopening, @mike-north!)

**Comment by boris-petrov** [comment]
I believe this issue is no longer relevant with the new Ember preview types.
