### ISSUE TITLE
ember-cli-typescript@2.0.0-beta.3 using ember-decorators in an workspace addon throws exception

### ISSUE THREAD

**Issue by theseyi** [typed-ember/ember-cli-typescript#366]
### Please paste the output of `ember -v` here
ember-cli: 3.5.0
node: 8.11.3
os: darwin x64

### Please paste the output of `tsc -v` here
Version 3.1.6

### Please paste your `tconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>
{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitOnError": true,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "lib": ["es2017.object", "es2016", "dom", "dom.iterable", "scripthost"],
    "listEmittedFiles": false,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "paths": {
      "dummy/tests/*": ["tests/*"],
      "dummy/*": ["tests/dummy/app/*", "app/*"],
      "*": ["types/*"]
    }
  },
  "include": ["app/**/*", "addon/**/*", "tests/**/*", "types/**/*", "test-support/**/*", "addon-test-support/**/*"]
}

  
  
</pre></details>

<details><summary><b>My tslint.json or eslint.json</b></summary><pre>
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  plugins: [
    'ember'
  ],
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended'
  ],
  env: {
    browser: true
  },
  rules: {
  },
  overrides: [
    // node files
    {
      files: [
        'index.js',
        'testem.js',
        'ember-cli-build.js',
        'config/**/*.js',
        'tests/dummy/config/**/*.js'
      ],
      excludedFiles: [
        'app/**',
        'addon/**',
        'tests/dummy/app/**'
      ],
      parserOptions: {
        sourceType: 'script',
        ecmaVersion: 2015
      },
      env: {
        browser: false,
        node: true
      },
      plugins: ['node'],
      rules: Object.assign({}, require('eslint-plugin-node').configs.recommended.rules, {
        // add your custom rules and overrides for node files here
      })
    },

    // test files
    {
      files: ['tests/**/*.js'],
      excludedFiles: ['tests/dummy/**/*.js'],
      env: {
        embertest: true
      }
    }
  ]
};

  

</pre></details>

### What are instructions we can follow to reproduce the issue?
```sh
git clone https://github.com/dfreeman/ember-workspace-playground.git
yarn
cd addon-a
ember install ember-decorators --save
./node_modules/.bin/ember test
```

##### Reproduction Case
If you can, please try to fork [this codesandbox](https://codesandbox.io/s/github/mike-north/ember-new-output/tree/ts), and give us an example that demonstrates the problem. Paste the link below so that we can see what's going on

**Link: ** <your link here>

### Now about that bug. What did you expect to see?

Expected to be able to invoke ember-decorators in nested workspace addon

### What happened instead?

```sh
➜  addon-a git:(master) ✗ ./node_modules/.bin/ember test
Environment: test
cleaning up...
Build Error (broccoli-persistent-filter:Babel > [Babel: addon-a]) in dummy/addon-a/tests/addon.lint-test.js

The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.


Stack Trace and Error Report: /var/folders/wg/5pdyslhx5zz9n97j4q334_6w000p7_/T/error.dump.c31eafb6c532998ef878ba9d3e3fad2b.log
```

**Comment by theseyi** [comment]
@dfreeman thanks for responding. Hmmm... I'll try to dive in more, but if I downgrade to ember-cli-typescript@latest in just that nested addon-a directory (1.5.0), this issue does not happen?

downgrade in nested addon
```sh
=> Found "ember-cli-typescript@2.0.0-beta.2"
info Has been hoisted to "ember-cli-typescript"
info Reasons this module exists
   - "workspace-aggregator-45a28dc0-7894-4e16-b632-9e0c4076896c" depends on it
   - Hoisted from "_project_#application#ember-cli-typescript"
   - Hoisted from "_project_#addon-b#ember-cli-typescript"
info Disk size without dependencies: "528MB"
info Disk size with unique dependencies: "2GB"
info Disk size with transitive dependencies: "8.23GB"
info Number of shared dependencies: 57
=> Found "addon-a#ember-cli-typescript@1.5.0"
info This module exists because "_project_#addon-a" depends on it.
info Disk size without dependencies: "216MB"
info Disk size with unique dependencies: "4.16GB"
info Disk size with transitive dependencies: "29.79GB"
info Number of shared dependencies: 168
✨  Done in 1.96s.
```

**Comment by chriskrycho** [comment]
So it's likely *surfaced* by use of the ember-cli-typescript v2 beta because of our switch to using Babel, but since we're not actually touching that dependency, it's probably not something we're doing that *causes* it. (We're happy to dig in further after coordinating with @pzuraq and co. of course!)

**Comment by theseyi** [comment]
Thanks guys
