### ISSUE TITLE
make ember-cli-typescript-blueprints optional

### ISSUE THREAD

**Issue by championswimmer** [typed-ember/ember-cli-typescript#367]
### Please write a user story for this feature

There are cases like this 

- I am using both js and ts files in my project
- I am using `ember-decorators` and do not want to use `extends Object.extend({})` syntax and simple use `extends Object {}` syntax

What I would prefer is that I can use the older js blueprints or the `ember-decorators` blueprints and not use ts blueprints. 

So when installing if `ember-cli-typescript` asks me if I want `ember-cli-typescript-blueprints`  instead of always installing, it would be better.

**Comment by chriskrycho** [comment]
Thanks for this suggestion! It’s a good call. If you feel like opening a PR, we’d be really happy to review and work with you to get it merged! Otherwise we’ll see about getting to it... *at some point*.

**Comment by dfreeman** [comment]
Just to clarify the current status quo:
 - in 1.x, installing `ember-cli-typescript` brings in the blueprints and the user has no control
 - in 2.x, installing `ember-cli-typescript` automatically adds the blueprints as a host dependency, but users can opt out by removing it from their `package.json`

**Comment by mike-north** [comment]
> in 2.x, installing ember-cli-typescript automatically adds the blueprints as a host dependency, but users can opt out by removing it from their package.json

The status quo is the correct behavior in v2. Consumers may want to "opt out" but they should get TS blueprints by default.

We'd also probably end up convincing @championswimmer to keep them around after our work on #364 - where we fully embrace decorators as part of the ember-cli-typescript experience. imo the blueprints would end up being exactly what he wants. 

I don't think any action is required here, unless we want to consder back-porting something to the v1 release series

**Comment by championswimmer** [comment]
Ok since 2.0.0-x is still in beta, I didn't notice the new behaviour in 2.0. 

It is completely acceptable to me what 2.0 does. (Probably adding in the documentation that removing it simply from package.json is enough should be good)

**Comment by chriskrycho** [comment]
Awesome, glad to hear that solves it well for you – and no worries about not knowing just exactly what things are coming in v2.0! 😆
