### ISSUE TITLE
Remove pre/post build hooks

### ISSUE THREAD

**Issue by alexlafroscia** [typed-ember/ember-cli-typescript#438]
### Please write a user story for this feature

Follow the form

> *As a **role**, I want **feature** so that **reason**.* 

As an addon author, I _don't_ want the old `ember ts:precompile` and `ember ts:clean` hooks to run when publishing, because that shouldn't be necessary any longer in the V2 beta.

***

I've been using `ember-cli-typescript@beta` in one of my addons to great success. It seems like `e-c-t` still adds the `prepublishOnly` and `postpublish` hooks when running 

```bash
ember install ember-cli-typescript@beta
```

I don't think that's necessary anymore, as the transformation is run by the host app now; it doesn't need to be run before publishing. 

I wanted to confirm before making a PR to remove that code from the blueprint. With that, I'm happy to submit a fix!

**Comment by dfreeman** [comment]
Thanks for filing this @alexlafroscia! We actually do still need `ts:precompile` and `ts:clean` in the v2 world to place `.d.ts` files in the correct location for the consuming application.

In order for consumers of an addon to know that the file at `addon/services/my-service.ts` is available for import at `my-cool-addon/services/my-service`, the `.d.ts` file needs to be in a different place than the source `.ts` ones. We may be able to revisit this in the future as module unification lands, but for now I don't think we can get rid of the publish hooks.

**Comment by chriskrycho** [comment]
I'll elaborate on Dan's answer to note that the consequence of what he said here:

> In order for consumers of an addon to know that the file at addon/services/my-service.ts is available for import at my-cool-addon/services/my-service, the .d.ts file needs to be in a different place than the source .ts ones.

…is that all the nice features like autocomplete, etc. don't work unless we do this, because the import location for an addon is not the same as the on-disk location for the addon until MU lands.
