### ISSUE TITLE
Temp directory

### ISSUE THREAD

**Issue by janmisek** [typed-ember/ember-cli-typescript#443]
First of all thanks for this wonderful addon !!!

I am using own ember-cli toolchain extension to have `my-project/tmp` directory on *mem mount point*. I discovered that there are `e-c-ts*` directories created in system `/tmp' directory. would it be possible to somehow configure this tmp path. 

If path would be configurable, I will be able to set the tmp to specific directory in `my-project/tmp` or in specific system tmp subdirectory which will be memory mount point.

If you agree I will implement it myself and submit pr. I need only hint where to look for it.

Thanks in advance.

**Comment by mike-north** [comment]
Starting with v2 of this addon, this project is responsible for very little in terms of file creation, and does nothing special with the `tmp` folder. Have you tried the latest v2 beta out, to see if it aligns with your custom tooling?

**Comment by janmisek** [comment]
No I havent tried because its based on babel and I saw there is alot of issues just in progress. I am starting with typescript in very large existing project and I want it to go smoothly. Therefore I will migrate to 2 when its stable. 

But could you please point me where in source code of ember-cli-typescript version 1.x is this usage of dir `/tmp/e-c-ts*` defined. I was not able to find it myself.

Thanks

**Comment by mike-north** [comment]
@janmisek Because of the way ember-cli's and Broccoli come together to form an asset pipeline, no addon specifies the location, or is even aware of a `tmp` folder.

All addons of this type typically receive a broccoli tree and emit an altered broccoli tree. For this reason, there's no code in this project (either for v1 or v2) that I could point you to.

**Comment by chriskrycho** [comment]
Following up on this: @janmisek, given that we have no particular control over how we handle `tmp` in the v2 and that we're in the process of taking that from RC to full release, I'm closing this issue. Please feel free to reopen if you discover that there's something specific to this addon that *does* affect your custom `tmp` directory handling in the v2 release candidate, though!
