### ISSUE TITLE
Generated violates RFC 337 native classes constructor

### ISSUE THREAD

**Issue by xg-wang** [typed-ember/ember-cli-typescript#476]
### Please paste the output of `ember -v` here
ember-cli: 3.5.1
node: 11.2.0
os: darwin x64

### Please paste the output of `tsc -v` here
Version 3.1.4

### What are instructions we can follow to reproduce the issue?
Repro in README: https://github.com/xg-wang/__ts-property-repro
Fresh project with ember-cli-typescript@2.0.0-beta.3

### Now about that bug.
Per [RFC 337](https://github.com/emberjs/rfcs/pull/337), we should be using `init` rather than `constructor` as:

```typescript
export default class S extends Service.extend({
  private a!: string;
  init() {
    super.init();
    this.a = 'inited';
  }
  getA() {
    return this.a || 'not inited';
  }
}
```

This code is later transpiled to:

```js
  class S extends Ember.Service.extend({// anything which *must* be merged to prototype here
  }) {
    constructor(...args) {
      super(...args);
      // Notice:
      // This will reset a as a member property
      this.a = void 0;
    }

    // normal class body definition here
    init() {
      super.init();
      this.a = 'inited';
    }

    getA() {
      return this.a || 'not inited';
    }

  }
```

While ember-cli-typescript doesn't explicitly says we should be using `constructor`, the "Typing Your Ember" blog series are giving examples of `constructor` - which worked around the issue.

**Comment by mike-north** [comment]
We dug into this and discovered that it can only be reproduced in versions of ember that predate the changes described in RFC-337. In current ember-release, init() happens after the constructors, not within the constructors.

**Comment by chriskrycho** [comment]
Also note that I'll be adding a further update post to the series soon to help clarify this, now that 3.6 and RFC 337 are live in the world. Thanks for the report!

**Comment by mike-north** [comment]
thank you @chriskrycho!
