### ISSUE TITLE
Provide better feedback for mis-configuration in addons

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#497]
### Please write a user story for this feature

Follow the form

> As an **addon author**, I want **to receive a clear and actionable error message in the event that my e-cli-ts configuration is incorrect (i.e., `dependencies` vs `devDependencies` issues)** so that **I don't spin my wheels for a long time trying to figure out what's wrong and how to fix it**.

Related: #496 
CC @alexlafroscia

**Comment by alexlafroscia** [comment]
This would be a huge win -- maybe the addon can check as part of the `included` hook whether the host is an addon, and then read the `package.json` to check which it's installed into?

**Comment by chriskrycho** [comment]
Seems reasonable. We're already doing some checking during initialization on Ember CLI version number; doing a further check on that would be a nice little DX win. Feel like PR-ing against the `v2` branch, @alexlafroscia?

**Comment by alexlafroscia** [comment]
Yeah, sure!

**Comment by chriskrycho** [comment]
Resolved by #498.
