### ISSUE TITLE
Ember generate should output typescript files

### ISSUE THREAD

**Issue by dwickern** [typed-ember/ember-cli-typescript#52]
# Original content

It would be nice to output `.ts` instead of `.js`

For reference see how coffeescript does this in https://github.com/kimroen/ember-cli-coffeescript/tree/master/blueprints

# Quest (added by [@chriskrycho] 2018/02/08)

[@chriskrycho]: https://github.com/chriskrycho

Let's convert some generators!

The basic strategy you should use is—**start by commenting that you're taking a generator on this thread (and look to make sure it hasn't been taken before you start in on one).** Then:

0. Fork the ember-cli-typescript repo on GitHub.
1. Clone ember-cli-typescript and create a new branch for your work.
2. Clone the Ember or Ember Data repo to have a point for comparison.
3. Run `ember generate blueprint <blueprint name>`. For example, to create the blueprint for a `component`, run `ember generate blueprint component`. (This will make sure you get the test generated in the `node-tests` directory.)
4. Copy the contents of the specific blueprint you just generated from the `blueprints` directory in the Ember or Ember Data over the blueprint you just generated.
5. Rename the generated JavaScript file to TypeScript.
7. Write a test to verify that you generate what you think you do (and that they represent best practices for TypeScript).
6. Update the blueprint contents to pass the test and match best practices.
8. Commit and push the branch to your fork, and open a PR!

For example, here's the process I followed for an Ember `Route`. On the command line:

```sh
$ git clone https://github.com/typed-ember/ember-cli-typescript.git
$ git clone https://github.com/emberjs/ember.js.git
$ cd ember-cli-typescript
$ git checkout --branch add-route-generator
$ yarn
$ ember generate blueprint route
$ cp -r ../ember.js/blueprints/route/* ./blueprints/route/
$ cd blueprints/route/files/__root__/__path__/
$ mv __name__.js __name__.ts
$ cd ../../../../..
```

Next, I opened `node-tests/blueprints/route-test.js` and added some checks to make sure it generates what I think it will:

```diff
'use strict';

const blueprintHelpers = require('ember-cli-blueprint-test-helpers/helpers');
const setupTestHooks = blueprintHelpers.setupTestHooks;
const emberNew = blueprintHelpers.emberNew;
const emberGenerateDestroy = blueprintHelpers.emberGenerateDestroy;

const expect = require('ember-cli-blueprint-test-helpers/chai').expect;

describe('Acceptance: ember generate and destroy route', function() {
  setupTestHooks(this);

-   it('route foo', function() {
+   it('route just-like-home', function() {
-     let args = ['route', 'foo'];
+     let args = ['route', 'just-like-home'];

    // pass any additional command line options in the arguments array
    return emberNew()
      .then(() => emberGenerateDestroy(args, (file) => {
-         // expect(file('app/type/foo.js')).to.contain('foo');
+         const generated = file('app/routes/just-like-home.ts');
+         expect(generated).to.contain('class JustLikeHome extends Route');
    }));
  });
});
```

I ran the test by doing `yarn run nodetest` on the command line, and the `route just-like-home` test failed, as expected. So I opened `blueprints/route/files/__root__/__path__/__name__.ts` in my editor and changed the contents:

```diff
import Route from '@ember/routing/route';

- export default Route.extend({
+ export default class <%= classifiedRouteName %> extends Route.extend({
+     // anything which *must* be merged to prototype here
- });
+ }) {
+     // normal class body definition here
+ }
```

Then I saved the file, and ran `yarn run nodetest` again, and everything passed!

Finally, I committed my changes, pushed them, and created [this PR].

[this PR]: https://github.com/typed-ember/ember-cli-typescript/pull/96

## Ember

- [x] acceptance-test
- [x] component
- [x] component-addon
- [x] component-test
- [x] controller
- [x] controller-test
- [x] helper
- [x] helper-addon
- [x] helper-test
- [x] initializer
- [x] initializer-addon
- [x] initializer-test
- [x] instance-initializer
- [x] instance-initializer-addon
- [x] instance-initializer-test
- [x] mixin
- [x] mixin-test
- [x] route
- [x] route-addon
- [x] route-test
- [x] service
- [x] service-test
- [x] template
- [x] test-framework-detector.js
- [x] test-helper
- [x] util
- [x] util-test

## Ember Data

- [x] adapter
- [x] adapter-test
- [x] model
- [x] model-test
- [x] serializer
- [x] serializer-test
- [x] transform
- [x] transform-test

**Comment by chriskrycho** [comment]
Some reference material to look through later, courtesy of @pixelhandler:

- [implementation](https://github.com/pixelhandler/ember-jsonapi-resources/tree/master/blueprints)
- [discussion](https://guide.ember-jsonapi-resources.com/generator.html)

**Comment by QuantumInformation** [comment]
Great idea.

**Comment by tansongyang** [comment]
PR for `component`: #97

**Comment by tansongyang** [comment]
PR for `helper`: #98

**Comment by MarcoUmpierrez** [comment]
PR for `controller`: #101

**Comment by pixelhandler** [comment]
@chriskrycho regarding those links I sent previously, the `generator` one no longer works as I didn't renew that domain, see https://pixelhandler.gitbooks.io/ember-jsonapi-resources-guide/content/generator.html instead. 

What I did in that repo was copy the default generators and fit them to the purpose of my addon, see `implementation` examples here https://github.com/pixelhandler/ember-jsonapi-resources/tree/master/blueprints

**Comment by tansongyang** [comment]
PR for `template`: #103

**Comment by chriskrycho** [comment]
@pixelhandler thanks for the update! And that’s exactky our strategy here, as you’ll note!

@tansongyang I will gander shortly!

**Comment by tansongyang** [comment]
PR for `util` and `util-test`: #104

**Comment by dfreeman** [comment]
Playing with the generators now, I believe we don't actually want to override the `*-addon` blueprints.

Those are the ones that generate the one-line re-export files in addons' `app/` trees, and since we don't process TS there, we likely want to just fall through to the default implementation in CLI the creates `.js` files.

**Comment by championswimmer** [comment]
FYI this somehow isn't working with Ember CLI 3.x though. 
Not sure why.
