### ISSUE TITLE
ts:precompile fails when using qunit-dom

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/ember-cli-typescript#568]
### Please paste the output of `ember -v` here
```
ember-cli: 3.7.1
node: 10.11.0
os: darwin x64
```

### Please paste the output of `tsc -v` here

Version 3.2.4

### Please paste your `tconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>My tsconfig.json</b></summary><pre>

{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "skipLibCheck": true,
    "paths": {
      "dummy/tests/*": [
        "tests/*"
      ],
      "dummy/*": [
        "tests/dummy/app/*",
        "app/*"
      ],
      "ember-loading": [
        "addon"
      ],
      "ember-loading/*": [
        "addon/*"
      ],
      "ember-loading/test-support": [
        "addon-test-support"
      ],
      "ember-loading/test-support/*": [
        "addon-test-support/*"
      ],
      "*": [
        "types/*"
      ]
    },
    "experimentalDecorators": true
  },
  "include": [
    "app/**/*",
    "addon/**/*",
    "tests/**/*",
    "types/**/*",
    "test-support/**/*",
    "addon-test-support/**/*"
  ]
}

  
</pre></details>

<details><summary><b>My eslint.json</b></summary><pre>

module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  plugins: [
    'ember'
  ],
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended'
  ],
  env: {
    browser: true
  },
  rules: {
  },
  overrides: [
    // node files
    {
      files: [
        '.eslintrc.js',
        '.template-lintrc.js',
        'ember-cli-build.js',
        'index.js',
        'testem.js',
        'blueprints/*/index.js',
        'config/**/*.js',
        'tests/dummy/config/**/*.js'
      ],
      excludedFiles: [
        'addon/**',
        'addon-test-support/**',
        'app/**',
        'tests/dummy/app/**'
      ],
      parserOptions: {
        sourceType: 'script',
        ecmaVersion: 2015
      },
      env: {
        browser: false,
        node: true
      },
      plugins: ['node'],
      rules: Object.assign({}, require('eslint-plugin-node').configs.recommended.rules, {
        // add your custom rules and overrides for node files here
      })
    }
  ]
};

</pre></details>

### What are instructions we can follow to reproduce the issue?
```sh
ember addon sample; cd ./sample # Create a new ember addon
ember install ember-cli-typescript # Set up typescript support

Add a test using qunit-dom (i.e. assert.dom())

ember ts:precompile

```

### Now about that bug. What did you expect to see?

Compiles without errors.

### What happened instead?

```
 error TS2339: Property 'dom' does not exist on type 'Assert'.
```

`qunit-dom` has TS typings, and correctly declares `assert.dom` [here](https://github.com/simplabs/qunit-dom/blob/master/lib/qunit-dom.ts#L5-L9). And this is working fine during development (i.e. `tsc --noEmit`).  

But AFAICT `--allowJs false` ([here](https://github.com/typed-ember/ember-cli-typescript/blob/v2/ts/lib/commands/precompile.ts#L28)) will make TS ignore the typings file in `node_modules` (note: the test are not explicitly importing any types from `qunit-dom`!). 

I was able to fix this by adding `node_modules/qunit-dom/dist/qunit-dom.d.ts` to `include` in my `tsconfig.json`. But would be nice if this works out of the box. Otherwise any TS addon using qunit-dom (which is part of the blueprint now) would probably run into this.

Should we add this to `tsconfig.json` automatically as part of the blueprint when `qunit-dom` is detected. Or any other way to fix this? 

/cc @turbo87

**Comment by Turbo87** [comment]
did you see https://github.com/simplabs/qunit-dom#typescript?

**Comment by simonihmig** [comment]
> did you see https://github.com/simplabs/qunit-dom#typescript?

Oh yes, right. Forgot about this. But I *did* have it. So my remark above about not explicitly importing anything from qunit-dom is apparently wrong, but the ts:compile step failed nevertheless.

**Comment by chriskrycho** [comment]
Hmm. I'll try this this afternoon – we used it in an app *just fine*, so maybe this is addon-specific, or perhaps there's a missing documentation piece, or maybe something else! 🤔

**Comment by mike-north** [comment]
I can't reproduce this w/ either ember-cli-ts@1 or ember-cli-ts@2. @simonihmig can you create a repo where this problem arises, so we can investigate?

**Comment by simonihmig** [comment]
> can you create a repo where this problem arises, so we can investigate?

@mike-north I encountered this with this addon: https://github.com/kaliber5/ember-loading

I added this line: https://github.com/kaliber5/ember-loading/blob/master/tsconfig.json#L56
Without it `ember ts:precompile` was failing with the aforementioned error.

**Comment by mike-north** [comment]
thanks for the repro case!

Fix here: https://github.com/kaliber5/ember-loading/pull/1

Root cause: TS has to find augmentation(s) one way or another. You've figured out that you can explicitly list files for TS to read, but the more ergonomic way is via ES imports.

You only have to do this once (i.e., in one test, or one test helper), because the augmentations happen globally

**Comment by simonihmig** [comment]
> Looks like the `qunit-dom` readme is pretty clear on this

> Rename your tests/test-helper.js to .ts if you do not have such a file yet.

Oh geez, you are right. I missed that somehow. 🤦‍♂️

Renaming that to .ts fixed this indeed. I guess I stopped worrying about it when I added the import to the .js file, which did fix the type error for my normal IDE integration and `tsc` without the `--allowJs false`. 

Thanks a bunch for your help here, and sorry for my confusion!
