### ISSUE TITLE
types and documentation for propertydecorator need to be added or updated

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#581]
Decorators work as per documentation in 1.5.0, but in 2.0 they use the new syntax as used in ember-decorators. 

This is a breaking change that isn't in the 2.0 release notes.

The documentation and examples need to be updated, and the ClassDecorator, PropertyDecorator and MethodDecorator types (and their associated Descriptor types) need to be defined.

**Comment by chriskrycho** [comment]
@BryanCrotaz thanks for opening this issue! A couple notes and questions:

1. Can you specify docs and examples that don't work? I've been using those without issue on a number of projects, so I'm curious what you ran into.

2. Those types are *way* outside the responsibility of this project!
