### ISSUE TITLE
Live-reload doesn't work with changes to addon in a consuming app

### ISSUE THREAD

**Issue by anmaikul** [typed-ember/ember-cli-typescript#583]
### Please paste the output of `ember -v` here
ember-cli: 3.5.1
node: 11.2.0
os: darwin x64

### Please paste the output of `tsc -v` here
Version 3.3.3

### Please paste your `tconfig.json` and `tslint.json` or `eslint.json` (if applicable) below

<details><summary><b>test-app tsconfig.json</b></summary><pre>

{ 
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "paths": {          
                        "test-app": [
                                "app/*",
                                "/Users/mkan/tests/test-addon/*"
                        ],
                        "test-addon/*": [
                                "/Users/mkan/tests/test-addon/addon/*"
                        ],
                        "test-addon": [
                                "/Users/mkan/tests/test-addon/addon"
                        ],
                        "*": [  
                                "types/*"
                        ]
    }
  },
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*",
    "/Users/mkan/tests/test-addon/app",
                "/Users/mkan/tests/test-addon/addon"
  ]
}

  
</pre></details>

<details><summary><b>test-addon tsconfig.json</b></summary><pre>

{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "paths": {
      "dummy/tests/*": [
        "tests/*"
      ],
      "dummy/*": [
        "tests/dummy/app/*",
        "app/*"
      ],
      "test-addon": [
        "addon"
      ],
      "test-addon/*": [
        "addon/*"
      ],
      "test-addon/test-support": [
        "addon-test-support"
      ],
      "test-addon/test-support/*": [
        "addon-test-support/*"
      ],
      "*": [
        "types/*"
      ]
    }
  },
  "include": [
    "app/**/*",
    "addon/**/*",
    "tests/**/*",
    "types/**/*",
    "test-support/**/*",
    "addon-test-support/**/*"
  ]
}
</pre></details>

### What are instructions we can follow to reproduce the issue?
1. Create test app:
```sh
ember new test-app; cd ./test-app # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
```

2. Create test add-on: 
```sh
cd .. 
ember new test-addon; cd ./test-addon # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
```

3. Link `test-addon` in `test-app`:
```sh
npm link
cd ../test-app
npm link test-addon
```
4. Copy `tsconfig.json` into respective project base dir.

6. Add add-on to `test-app`'s `package.json`:
```
'test-addon': '0.0.0',
```
5. Create test component in `test-addon`, `test-component.ts`, and add a message:

```sh
ember g component test-component.ts
```

In test-addon/addon/components/test-component.ts:
```js
import Component from '@ember/component';
// @ts-ignore: Ignore import of compiled template
import layout from '../templates/components/test-component';

const message: String = "Hello from addon!";

export default class TestComponent extends Component.extend({
  message
}) {
  layout = layout;
  // normal class body definition here

```

In test-addon/addon/templates/components/test-component.hbs:
```html
<h1 id="title">{{message}}</h1>
{{yield}}
```

6. Display message in `test-app`:

In test-app/app/templates/application.hbs:
```
{{test-component}}

{{outlet}}

```

7. Build & run `test-app`:

```
ember serve -p 4201 
```

8. Navigate to `localhost:4201`.

9. Change the message in test-component.ts & save. App dos not reload automatically, and `ember serve` must be restarted for changes to take effect.

### Now about that bug. What did you expect to see?
I expect the app to live reload when changing a TS file in my addon.

### What happened instead?
ember-cli detects the TS file change, but does not recompile it.

Sample output:
```
file changed components/test-component.ts

Build successful (2301ms) – Serving on http://localhost:4201/



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Vendor JS (1)                                 | 554ms               
Funnel (73)                                   | 205ms (2 ms)        
ember-browserify (2)                          | 161ms (80 ms)       
Funnel: Addon JS (94)                         | 154ms (1 ms)        
Concat: Vendor Styles/assets/vendor.css (1)   | 119ms
```

**Comment by chriskrycho** [comment]
Thanks for the report! Can you try this against the 2.0 RC by doing `ember install ember-cli-typescript@next`? I *think* it will have fixed this.

**Comment by anmaikul** [comment]
Thanks for the work with the latest `ember-cli-typescript`! 
I installed the 2.0 RC of `ember-cli-typescript`, and also upgraded `ember-cli-babel` to 7. I also moved `ember-cli-babel` from a dev dependency to dependency in the addon `package.json`, and moved the addon in the app to a dependency. 

It does look like it's picking up my changes to the addon TS files!
 
However, nothing is rendered, and I get the following error in the console: 

```
Uncaught Error: Could not find module `test-addon/components/test-component` imported from `test-app/components/test-component`
```
I double checked all the `paths` in the app's `tsconfig.json`. Any idea what's causing this?

**Comment by chriskrycho** [comment]
A couple troubleshooting steps:

1. Run `ember generate ember-cli-typescript` if you did the installation via `yarn` or `npm` instead of via `ember install`.
2. Check that your `dependencies` are set up correctly.
3. Make sure that your addon's `app` directory includes only `.js` files: the pipeline gets confused if there are both `.js` and `.ts` files there when it merges addon `app` and regular `app` directories.

**Comment by anmaikul** [comment]
Step 2 did it for me. (Moving `ember-cli-typescript` and `ember-cli-babel` from `devDependences` to `dependencies`)

Thanks for your help!
