### ISSUE TITLE
Link to wiki from readme is broken

### ISSUE THREAD

**Issue by ryanlabouve** [typed-ember/ember-cli-typescript#60]
There's a link on the readme that's currently that supposed to go to the wiki that's currently broken.

`Please see [the wiki](https://github.com/emberwatch/ember-cli-typescript/wiki/tsconfig-how-to) for additional how to tips from other users or to add your own tips. If an use case is frequent enough we can codify in the plugin.`

Any way I can help with this? I'd be happy to 😁

**Comment by chriskrycho** [comment]
Oh, good call-out! Best thing you could do is submit a PR to remove that line entirely—we're not actually using the wiki at present!
