### ISSUE TITLE
Fix support for services with mixins

### ISSUE THREAD

**Issue by phil294** [typed-ember/ember-cli-typescript#604]
Followup to https://github.com/typed-ember/ember-cli-typescript/issues/177

While
```
export default class MyComponent extends Component.extend(MyMixin) {}
```

now works, 

```
export default class MyService extends Service.extend(MyMixin) {}
```

once again fails with

> Class static side 'typeof ConfigService' incorrectly extends base class static side 'Readonly<typeof Service>'.
  Types of property 'prototype' are incompatible.
    Type 'ConfigService' is missing the following properties from type 'Service': get, getProperties, set, setProperties, and 15 more.ts(2417)

Can this be fixed? Is there a workaround?

### Which package(s) does this problem pertain to?
  - [x] @types/ember
  - [x] @types/ember__service

**Comment by phil294** [comment]
This issue is invalid. The above *does* work.

**Comment by chriskrycho** [comment]
No problem – thanks for both opening and closing!
