### ISSUE TITLE
Broken link in update-docs branch

### ISSUE THREAD

**Issue by acorncom** [typed-ember/ember-cli-typescript#609]
Expected: As an **guides reader** of the new ember-cli-addon-docs guides, I want to be able to **view a list of addons with known type definitions**, so that **I understand what my options are**

Actual: When visiting https://typed-ember.github.io/ember-cli-typescript/versions/update-docs/docs/ts-guide/using-ts-effectively#install-other-types- and clicking the ** a list of addons with known type definitions** link, I'm taken to a page that doesn't work

/cc @chriskrycho 

Those docs are looking sharp!

**Comment by chriskrycho** [comment]
Ah, thank you for catching this! I'll get it in before we merge!
