### ISSUE TITLE
Document recommended linting setup

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/ember-cli-typescript#637]
We should document a recommendation for setting up linting, including things like:
 - Installing and configuring [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin)
 - Updating the `lint:js` script to ensure it includes the right extensions
 - Configuring popular editors to run ESLint against `.ts` files

Parts of this can also probably be set up as part of the default blueprint, or a supplemental opt-in one.

**Comment by dfreeman** [comment]
Related: #963

**Comment by sukima** [comment]
What is the status of this? I'm still running into this on a fresh install.

**Comment by chriskrycho** [comment]
Recommended linting configuration is now (as of a few versions back in Ember and Ember CLI) built in out of the box via Ember's own blueprints when using `--typescript`. 🎉
