### ISSUE TITLE
Documentation update for template "layout" resolving

### ISSUE THREAD

**Issue by raido** [typed-ember/ember-cli-typescript#641]
I hit a confusing setup for components and "layout" resolving as paths for setup are misleading over here:

https://typed-ember.github.io/ember-cli-typescript/docs/ts-guide/current-limitations#templates

It should be updated as following:

`declare module 'app/templates/*' {` should be 
`declare module '<my-app>/templates/*' {`

`declare module 'addon/templates/*' {` should be 
`declare module '<my-addon>/templates/*' {`

Additionally we could actually automatically add "global.d.ts" file for templates if we detect that `ember-cli-htmlbars` is present in package.json `dependencies` for addons.

**Comment by chriskrycho** [comment]
Thanks so much for reporting this!

---

#643 will resolve the "generate this" side of it; I'll also try to tweak the docs next week!

**Comment by raido** [comment]
Is this relevant still or we can close?

**Comment by chriskrycho** [comment]
I think it can be closed! Thanks again!
