### ISSUE TITLE
[Test Infra] Use system tmp folder for node-test fixtures

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-typescript#645]
Currently test fixtures (for our mocha tests) are placed in the project root directory. This can cause tools like vscode to start indexing stuff. We should be following Broccoli 2.0's lead and putting any temporary files in the system/tmp folder rather than inside the project

**Comment by chriskrycho** [comment]
I have no idea what we actually do here at this point, but we now recommend that people switch to using `ember-cli-babel` for apps (as documented [here](https://github.com/babel/ember-cli-babel#enabling-typescript-transpilation)) and the rollup plugin configured as part of the v2 add-on build for add-ons, in conjunction with running `glint` or `tsc` directly on their projects. Accordingly, we are not investing further into maintenance in the fundamentals of e-c-ts, so I am closing this out!
