### ISSUE TITLE
Ember blueprint to create typing file

### ISSUE THREAD

**Issue by bakerac4** [typed-ember/ember-cli-typescript#650]
As a user, I want to be able to run `ember g type ember-intl` and have a folder with an index.d.ts file in an "ember-intl" directory created under `types`

**Comment by mike-north** [comment]
I'm not sure about this for two reasons

1. In the specific example mentioned, the meaningful fix would be to provide some real types in the `ember-intl` package, or publish a `@types/ember-intl`

2. Usually I look for blueprints to save users a significant amount of time by saving them from some non-trivial boilerplate. One way to think of the _value_ of a blueprint is as some function of `how much time it saves the user` ⨉ `how many times it's used per day`. Since this would be generating an empty file, and is used very infrequently (relative to a service, component, route blueprint) the value seems low.

**Comment by bakerac4** [comment]
@mike-north 

1. Yes, but I also didn't provide all types at once. I only added enough to remove the red lines in my project. So I really only added basic types for things Im actually using. While the "right" thing to do would be to go through, create a PR and flush out everything thats just not on my todo list.

2. Personally I would find that useful just because otherwise I have to create that structure myself. But You can also add something like the `model` blueprint has.

```
ember g type ember-intl interface:test
```
which would create an interface called test inside the `ember-intl` module and 
```
ember g interface ember-intl/test firstName:string lastName:string isPerson:boolean
```
would would create an interface called `test` with those properties and types

**Comment by chriskrycho** [comment]
@bakerac4 I'm broadly inclined to agree with @mike-north here, and we already have more maintenance problems than we've been able to handle in the blueprints repo.

That said: there's nothing at all stopping you from building exactly that addon yourself! Blueprints/generators for them should be able to be provided in a reasonably lightweight way (just more than we have bandwidth for), and we'd be more than happy to point people to such an addon if you built it.

**Comment by jamescdavis** [comment]
I'll also chime in and say that I agree with @mike-north and @chriskrycho. While I could *maybe* see some utility in a blueprint that does this, I don't think it belongs in the e-c-ts core blueprints. Putting type definition in `/types/` should really just be seen as a stop-gap until "real" type definitions are available (whether you create these or some other party). We should encourage working towards published type definitions. Also, unlike an Ember model, type definition structure is going to vary by package. Creating a blueprint to create arbitrary structure seems overly complex for what it does. IMHO, it'd just be easier and more straightforward to create the files and their contents by hand.

**Comment by chriskrycho** [comment]
Given we have a strong consensus from the maintainers here, I'm going to go ahead and close this. Thanks for the suggestion, @bakerac4!
