### ISSUE TITLE
Component.element has type Element but should have HTMLElement

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#676]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__component

`Component.element` has type `Element` but should have `HTMLElement` instead. Components' elements don't have anything else they could be so being more specific is better. For example, jQuery's types are generic on `HTMLElement` and when comparing against an Ember Componet's `element`, casts have to be made which is annoying and needless.

A nice overview of the DOM can be found [here](https://web.stanford.edu/class/cs98si/slides/the-document-object-model.html).

**Comment by chriskrycho** [comment]
@boris-petrov this is incorrect: `EmberComponent.element` can be *any* kind of `Element`. You can see this by doing this and checking the type of the element rendered to the page:

```js
import Component from '@ember/component';

export default Component.extend({
  tagName: 'svg'
})
```

If you then inspect the output and find that element, you'll see that `thatEl instanceof Element` is `true` and `thatEl instanceof HTMLElement` is `false` and `thatEl instanceof SVGElement` is `true`.

(Also, trust me when I say that the Ember TS crew has a pretty good idea of how the DOM works. 😉)

**Comment by boris-petrov** [comment]
@chriskrycho - you're right, thank you for the good example! I've never doubted that all of you know the DOM perfectly well, sorry if it sounded so! :)

**Comment by chriskrycho** [comment]
No worries! 😉
