### ISSUE TITLE
Run nightly build against upcoming releases

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#688]
We want to allow future versions of Ember, TS, etc. to fail even though we're testing against them (#687), but we also want to have regular checks so that we don't see those errors only on the event of a PR being opened. Run scheduled builds against upcoming releases, and (preferably) report any build failures loudly into Discord.

**Comment by mike-north** [comment]
>  we also want to have regular checks so that we don't see those errors only on the event of a PR being opened

Can you elaborate on this? Currently the _required_ builds are the ones that must pass in order to merge a PR (the e-cli and typescript betas are not included).

The main difference we're seeing now, compared to the previous travis-ci setup, is these failures are now surfaced in the pull request UI instead of buried in the CI status page (which we were unlikely to click on, if the single travis status showed "green").

**Comment by mike-north** [comment]
As for the direct ask of nightly builds, we already do this at 4am pacific time every day

<img width="1556" alt="Screen Shot 2019-04-17 at 8 59 58 PM" src="https://user-images.githubusercontent.com/558005/56336094-df6aa980-6153-11e9-801e-18c3f4537f80.png">

> report any build failures loudly into Discord.

If you mean the ember community Discord, we do not have sufficient discord permissions to facilitate this.

**Comment by chriskrycho** [comment]
> Personally, I want to see these failures. Particularly once the e-cli beta starts passing again, I definitely want it to be obvious if we're considering a merge that would cause it to start failing again. Do you have a different opinion?

I want two things (though I'm open to being persuaded otherwise):

1. I want to know about failures in upcoming releases independent of our happening to introduce a PR. It should be obvious when something besides our own change introduced the breakage.
2. The build status on our landing page *should not* show that we're failing simply because an upcoming version of Ember CLI has introduced breakage. We're *not* failing in that case.

> As for the direct ask of nightly builds, we already do this at 4am pacific time every day

Excellent! I did not realize this.

> If you mean the ember community Discord, we do not have sufficient discord permissions to facilitate this.

This [can be arranged](https://discordapp.com/channels/480462759797063690/480499718330253342/568792780449644565); hopefully we'll hear back on that request soon.

**Comment by chriskrycho** [comment]
We're happy with our CI setup at this point, even including the Discord notifications (which did eventually happen!).
