### ISSUE TITLE
Support for "yarn link" (or add whatever I misunderstood to documentation)

### ISSUE THREAD

**Issue by mblandfo** [typed-ember/ember-cli-typescript#695]
I am using ember-cli-typescript 1.5.0 (I can't use 2.x because we're on babel 6.x), but I suspect this will also reproduce in 2.x. 

I have an addon that is linked to my app (for local dev) using yarn link

This creates a symlink in node modules to the addon directory.

ember-cli-typescript has a prepublish script that builds my .ts files into .js, so when I am developing locally, prepublish doesn't get run, my .js do not get created, and the app crashes.

How is this supposed to work? Am I doing something unusual by trying to yarn link my addon?

https://stackoverflow.com/questions/55802021/yarn-link-doesnt-run-prepublish-script-so-what-else-can-i-do-to-develop-an-emb

Possibly similar issue: https://github.com/typed-ember/ember-cli-typescript/issues/368

**Comment by chriskrycho** [comment]
This actually *should* Just Work™ (more or less) correctly in v2—see [the docs on exactly this workflow](https://typed-ember.github.io/ember-cli-typescript/docs/ts-guide/with-addons#linking-addons).

**Comment by chriskrycho** [comment]
Beyond that, you can simply run `yarn ts:precompile` in your addon directory, possibly with a watcher like [`watchexec`](https://www.github.com/watchexec/watchexec) to trigger running it, as a workaround until you're able to upgrade.

**Comment by mblandfo** [comment]
Ok, thanks! I think I'll wait until we can use 2.x
