### ISSUE TITLE
Including ember-cli-typescript into an app with ember-cli-babel@7.7+ emits warnings

### ISSUE THREAD

**Issue by rwjblue** [typed-ember/ember-cli-typescript#707]
### What are instructions we can follow to reproduce the issue?

```
ember new test-ts-warning
cd test-ts-warning
ember install ember-cli-typescript
ember build
```

### Now about that bug. What did you expect to see?

No console warnings.

### What happened instead?

The following warnings are emitted:

```
WARNING: test-ts-warning has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
WARNING: test-ts-warning has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
```

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/typed-ember/ember-cli-typescript/pull/640

**Comment by bartocc** [comment]
#640 has been superseeded by #730

**Comment by chriskrycho** [comment]
Thanks for flagging it up, @bartocc! This is indeed *resolved* by #730, now closed.

**Comment by lolmaus** [comment]
Hi! I'm using `ember-cli-typescript@2.0.2` which seems to include this PR: https://github.com/typed-ember/ember-cli-typescript/commits/master?after=03134c31ab25ab7ffef60b6fee1b32cc9f1fadc1+104

But I'm still seeing this in the terminal: 

```
WARNING: wbc has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
WARNING: wbc has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
WARNING: wbc has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
WARNING: wbc has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
```

How to get rid of those?

I've checked `yarn.lock`, and the only addons using `class-properties` are `ember-cli-babel` and `ember-cli-typescript`.

**Comment by dfreeman** [comment]
@lolmaus v2.0.2 doesn't include a fix for this yet: https://github.com/typed-ember/ember-cli-typescript/commits/v2.0.2

Instead we opted to drop support for ember-cli-babel < 7.7.3 completely, which is a breaking change that's queued up with a few other things for a 3.0 release, which will hopefully be coming soon! We just have a few last things to wrap up in the meantime.

**Comment by lolmaus** [comment]
@dfreeman Thx for the clarification! 🙇 

CC @simonihmig @nickschot @andreasschacht
