### ISSUE TITLE
Typescript cannot resolve modules from ember-cli addons

### ISSUE THREAD

**Issue by inkless** [typed-ember/ember-cli-typescript#74]
When using ember-cli addons, even you've installed type definition file, typescript still cannot find the module.
For example, when using `ember-cli-htmlbar-inline-precompile` modules. Even you declare a module `htmlbar-inline-precomple` in your type definition file, since `node_modules/htmlbar-inline-precompile` does not exist, typescript cannot resolve it correctly.

Here's a working sample: https://github.com/inkless/ember-test-app
Type definition is here:
https://github.com/inkless/ember-test-app/blob/master/app/types/ember-shim.d.ts
Test code is here: https://github.com/inkless/ember-test-app/blob/master/tests/integration/components/apple-pie/component-test.ts

Typescript still produce error:

> WARNING: ember-test-app/tests/integration/components/apple-pie/component-test.ts(2,17): error TS2307: Cannot find module 'htmlbars-inline-precompile'.

![image](https://user-images.githubusercontent.com/2149223/30766538-9e3a6944-9faa-11e7-8a0c-cb70a94f8095.png)

**Comment by chriskrycho** [comment]
There's a nice solution for this now, since we ship type definition shims for `htmlbars-inline-precompile` with the latest version of the Ember typings.
