### ISSUE TITLE
JavaScript heap exceeded on ember serve

### ISSUE THREAD

**Issue by LucasHill** [typed-ember/ember-cli-typescript#744]
Having an issue when trying to serve an app which I just installed ember-cli-typescript into. The app is all JS currently, no TS. The app itself is fairly small but it depends on a large internal add-on we developed. The build fails quickly with a heap error. I can get the build to work by increasing node's heap limit. While this works, I feel like it probably shouldn't be happening? 

Thanks for this add-on, it seems great, looking forward to using it. 

Here's the output:

```
<--- Last few GCs --->

[20687:0x110000000]    57909 ms: Mark-sweep 1395.2 (1423.0) -> 1394.7 (1423.5) MB, 707.5 / 0.0 ms  (average mu = 0.113, current mu = 0.014) allocation failure scavenge might not succeed
[20687:0x110000000]    58599 ms: Mark-sweep 1395.4 (1423.5) -> 1395.0 (1424.0) MB, 681.8 / 0.0 ms  (average mu = 0.065, current mu = 0.012) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x29edd65be3d]
Security context: 0x1d5d7571e6e9 <JSObject>
    1: bindEachFunctionsFirst(aka bindEachFunctionsFirst) [0x1d5db773aa01] [/some/path/node_modules/typescript/lib/typescript.js:~28151] [pc=0x29edf5ba6dc](this=0x1d5deac026f1 <undefined>,nodes=0x1d5d1fe088a9 <JSArray[5]>)
    2: bindChildrenWorker(aka bindChildrenWorker) [0x1d5db773aac1] [/some/path...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/some/path/.nvm/versions/node/v10.16.0/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::
```
  ember-cli: 3.9.0
  node: 10.16.0
  os: darwin x64

tsc: 3.5.2
ember-cli-typescript: 2.0.1
ember-cli-typescript-blueprints: 2.0.0

##### Reproduction Case
This is a private repo so unfortunately I can't link it. Unsure how to reproduce otherwise. I tried with a fresh ember project on my machine and that does not reproduce the issue.

**Comment by dfreeman** [comment]
Hi @LucasHill, sorry you're running into this! As a first step, can you check to see if you see a similar OOM error when you invoke the TypeScript compiler directly?

```
node_modules/.bin/tsc --watch
```

**Comment by LucasHillDex** [comment]
I ended up figuring this out. We have multiple in house addons we use that are symlinked into the main ember project. The tsconfig.json that was generated was including all of these folders in "include" paths. I think this was causing it to get overwhelmed by perhaps trying to process all the node_modules in that addon. By reconfiguring the ts.config without those I was able to get the project to build. It's hard to create an example, and it's probably not a very common use case. Should I just close this?

**Comment by chriskrycho** [comment]
Thanks for following up! I'm going ahead and closing it, but we'll keep this in mind for reference for others (and there should be some search engine use from it). If you can identify the size at which it crashed, and report that upstream to the TypeScript team, I imagine that would help them a lot!
