### ISSUE TITLE
No type information for ember-load-initializers 

### ISSUE THREAD

**Issue by baron1405** [typed-ember/ember-cli-typescript#745]
### Which package(s) does this enhancement pertain to?
  - [X] Other: ember-load-initializers

### Please write a user story for this feature

The addon ember-load-initializers does not have a corresponding types package.

**Comment by ro0gr** [comment]
There is a pr with types https://github.com/ember-cli/ember-load-initializers/pull/111

**Comment by baron1405** [comment]
Thanks @ro0gr for the pointer. It sounds like I should just wait a bit for the next release of ember-load-initializers and I will get the types. If that is the case, it sounds like I should close this issue.

**Comment by ro0gr** [comment]
@baron1405 well, it's not merged yet and I'm not sure if it would. I'd keep the issue opened until it's truly solved.

**Comment by baron1405** [comment]
@ro0gr got it, thanks!

**Comment by baron1405** [comment]
Any update on this?

**Comment by msalahz** [comment]
Any update on this?

**Comment by chriskrycho** [comment]
Sorry, I just now caught up on the state of this. The answer is: when the upstream ships its types, this will be resolved, and since the intent is for that to happen, I see this as a duplicate and am closing it!
