### ISSUE TITLE
start() function isn't in @types/ember-mocha

### ISSUE THREAD

**Issue by richard-viney** [typed-ember/ember-cli-typescript#755]
Hi,

It seems that a type for the `start()` function is missing from `@types/ember-mocha` here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember-mocha/index.d.ts

In the app I work on we've added the following as a workaround in a `.d.ts` file:

```
declare module "ember-mocha" {
  export function start(): void
}
```

Version: `@types/ember-mocha@0.14.6`.

**Comment by chriskrycho** [comment]
Thanks for opening this! If you like, one of us will be happy to mentor you through getting the change into DefinitelyTyped!

**Comment by richard-viney** [comment]
Sounds good.

On closer inspection the full type definition is actually this:

```ts
declare module "ember-mocha" {
  interface StartOptions {
    loadTests?: boolean
    startTests?: boolean
  }

  export function start(options?: StartOptions): void
}
```

Could also add the definition for `startTests()` as it is also exported by `ember-mocha`:

```ts
declare module "ember-mocha" {
  export function startTests(): void
}
```

**Comment by chriskrycho** [comment]
ember-mocha has since been deprecated in favor of ember-qunit. People should switch to the maintained package. While PRs will still be accepted against the DefinitelyTyped definitions, I am closing this issue as no longer relevant. Thanks!
