### ISSUE TITLE
-private/transition.d.ts has a sequence member-variable

### ISSUE THREAD

**Issue by psbanka** [typed-ember/ember-cli-typescript#778]
### Which package(s) does this enhancement pertain to?

  - [X] @types/ember__routing

### Please write a user story for this feature

*As an **application developer who is intercepting a user attempting to navigate to a route that does not exist**, I want **the router to transition to a valid page instead of simply performing a 404** so that **the user can see something useful**.*

One solution to this is to require the use of the `sequence` attribute on a transition object [see this discussion](https://discuss.emberjs.com/t/how-do-i-handle-canceling-the-first-transition-on-page-load/4568). Of course, I would never import and use the private API.

However, for the completeness of typing, it would be handy if we could add the sequence value:

```sh
diff --git a/types/ember__routing/-private/transition.d.ts b/types/ember__routing/-private/transition.d.ts
```

```diff
index 027e913aca..1ea86fc7d1 100644
--- a/types/ember__routing/-private/transition.d.ts
+++ b/types/ember__routing/-private/transition.d.ts
@@ -17,6 +17,7 @@ export default interface Transition {
      * by initiating another transition while a previous one is underway.
      */
     abort(): Transition;
+    sequence: number;
     /**
      * Retries a previously-aborted transition (making sure to abort the
      * transition if it's still active). Returns a new transition that
```

**Comment by chriskrycho** [comment]
This was ultimately just a request to expose a private API, which we don't do. Closing accordingly.
