### ISSUE TITLE
Can we add `location` to the `route.d.ts` definition

### ISSUE THREAD

**Issue by psbanka** [typed-ember/ember-cli-typescript#779]
### Which package(s) does this enhancement pertain to?

  - [X] @types/ember__routing

### Please write a user story for this feature

*As an **app developer**, I want **to be able to see the router location** so that **i can *examine query parameters*.*

The `route.d.ts` file has a `location` member variable that can be used but does not have typings:

```sh
diff --git a/types/ember__routing/route.d.ts b/types/ember__routing/route.d.ts
index a07f802bb0..4a298bd8ee 100644
```

```diff
--- a/types/ember__routing/route.d.ts
+++ b/types/ember__routing/route.d.ts
@@ -5,6 +5,13 @@ import Evented from "@ember/object/evented";
 import { RenderOptions, RouteQueryParam } from "@ember/routing/types";
 import Controller, { Registry as ControllerRegistry } from '@ember/controller';

+interface AutoLocation {
+    getURL(): () => string;
+    rootURL: string;
+    history: any;
+    location: any;
+}
+
 /**
  * The `Ember.Route` class is used to define individual routes. Refer to
  * the [routing guide](http://emberjs.com/guides/routing/) for documentation.
@@ -59,6 +66,8 @@ export default class Route extends EmberObject.extend(ActionHandler, Evented) {
      */
     disconnectOutlet(options: string | { outlet?: string; parentView?: string }): void;

+    location: AutoLocation
+
     /**
      * A hook you can implement to convert the URL into the model for
      * this route.
```

**Comment by chriskrycho** [comment]
This is not public API, and we very intentionally *do not supply private API in the type definitions*. I'm closing this accordingly.

The `location` property is available [on the `RouterService`](https://api.emberjs.com/ember/3.11/classes/RouterService/properties/location?anchor=location) and [the `EmberRouter`](https://api.emberjs.com/ember/3.11/classes/EmberRouter/properties/location?anchor=location); prefer to use those as documented instead!
