### ISSUE TITLE
Official documentation indicates we should import `htmlSafe` from `@ember/template`

### ISSUE THREAD

**Issue by psbanka** [typed-ember/ember-cli-typescript#784]
### Which package(s) does this problem pertain to?

  - [X] @types/ember__string

### What are instructions we can follow to reproduce the issue?
add this line to any ember `.ts` file:

```ts
import { htmlSafe } from '@ember/template';
```

and you will get a TypeScript error despite the fact that [official documentation](http://api.emberjs.com/ember/3.11/functions/@ember%2Ftemplate/htmlSafe) indicates that this is where the import should come from. Instead, we have to import from `@ember/string`.

### Now about that bug. What did you expect to see?
Clean import with no TS errors.

### What happened instead?
TypeScript complains of not being able to find type info for `htmlSafe`

**Comment by chriskrycho** [comment]
Thank you for opening this! If you open a PR against DefinitelyTyped adding it (including some tests) we'd be happy to review!

**Comment by scottkidder** [comment]
I'm more than happy to take this on. What's the right thing to do here? Should I create a new package called ember__template or is is there some better approach?

**Comment by jamescdavis** [comment]
That's right! And then once we have that in, we'll need to [reference it from @types/ember](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/35362243fe1127a52b4129296c3ebd7e4594ac3f/types/ember/index.d.ts#L16-L30) so it gets installed automatically.

**Comment by scottkidder** [comment]
@jamescdavis Thanks for the confirmation! I put something together [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38571)

I was not sure if I should additionally remove or somehow deprecate the @ember/string/htmlSafe export?

**Comment by jamescdavis** [comment]
I added a couple of comments to the PR. As far as removing it from `@ember/string`, the API docs as late as Ember 3.7 [are conflicted](http://api.emberjs.com/ember/3.7/functions/@ember%2Ftemplate/htmlSafe) (and importing from `@ember/string` *does* work) so we should probably leave it there for now, but could (and should) change those to just re-export from `@ember/template`. I'm pretty sure there's no way to tell the TypeScript compiler that something is deprecated, but if you annotate with a JSDoc [@deprecated](https://jsdoc.app/tags-deprecated.html) tag, tslint (at least) can [detect that and warn](https://palantir.github.io/tslint/rules/deprecation/).

**Comment by mschorsch** [comment]
Possible duplicate #342

**Comment by jamescdavis** [comment]
Closed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38571
