### ISSUE TITLE
Merge ember-cli-typescript into ember-cli?

### ISSUE THREAD

**Issue by gossi** [typed-ember/ember-cli-typescript#80]
Hmm, I'm not quite sure with this issue. I'm just a ember consumer, with no background of ember internals at all. Yet I was about to use typescript in my project, I just started to use it and updated to ember 2.15 which crashed typescript support, see #77 . If I had my code written in typescript, it would me require to downgrade ember-cli back to the last working version. What this points out, is the reliability of ember-cli-typescript is questionable, which I think would be different if typescript was directly supported by ember-cli, which I guess would improve the idea to develop addons in typescript immense.

From what I read about ember and the direction ember is moving (e.g. glimmer) and I'm sure more parts of the whole ecosystem will turn over to typescript as well, this would require typescript support anyway, I was wondering if it might be an idea to think about merging ember-cli-typescript into ember-cli?

**Comment by chriskrycho** [comment]
At least at present, I don’t think that’s desired by the Ember CLI team. However, whether it might be possible in the medium-to-long-term future, I have no idea.

I’d note that the reliability of ember-cli-typescript isn’t really any more of a question than any other addon like it: you could run into the same sorts of problems if you were using ember-cli-coffeescript, or using custom Babel plugins that happened to have a bad interaction with Ember CLI in some way.

Closing per that (and looking forward to fixing #77 in the next week or so.)

**Comment by gossi** [comment]
Ok, thanks. Maybe I was to early or something ;)
