### ISSUE TITLE
Add generator blueprint for prototype extensions

### ISSUE THREAD

**Issue by dwickern** [typed-ember/ember-cli-typescript#88]
We should generate a `.d.ts` with prototype extensions.

Prototype extensions are controlled by `EXTEND_PROTOTYPES`:
https://guides.emberjs.com/v2.3.0/configuring-ember/disabling-prototype-extensions/

We can't conditionally enable types based on this so the best we can do is generate a `.d.ts` which the user can edit.

Array prototype extensions should be enabled by default for apps and disabled for addons. Function prototype extensions should be disabled by default probably. We haven't implemented string prototype extensions.

```ts
declare global {
    interface Array<T> extends Ember.ArrayPrototypeExtensions<T> {}
    interface Function extends Ember.FunctionPrototypeExtensions {}
}
```

**Comment by dfreeman** [comment]
> Function prototype extensions should be disabled by default probably.

AFAIK array prototype extensions are the only ones that aren't already deprecated/[slated for deprecation](https://github.com/emberjs/rfcs/pull/272), so it makes sense to me that they'd be the only ones enabled by default.

**Comment by dwickern** [comment]
Can a blueprint detect if it's an addon vs. app for the array prototype extensions?

**Comment by dfreeman** [comment]
In most cases yes, though the addon story for e-c-ts is a little bit of an oddball, since having it as a `devDependency` means it's technically only installed for the addon's dummy app. We may have to settle for checking if the project name is `dummy` and basing the decision on that.

**Comment by chriskrycho** [comment]
Looking at what I have for this in #108 and the discussion above: it looks like the function prototype extensions should probably be *included* but *commented out* to make it easy for people to “flip a switch” and turn them on?

**Comment by HodofHod** [comment]
Just a heads up: enabling `interface Function extends Ember.FunctionPrototypeExtensions { }` causes typing errors when using `ember-decorators`' class decorators for me.

`[ts]
Unable to resolve signature of class decorator when called as an expression.
  Type 'Function' is not assignable to type 'void | typeof Badge'.
    Type 'Function' is not assignable to type 'typeof TooltipBadge'.`

Hope this helps anyone coming across that issue.
