### ISSUE TITLE
README TOC is out of date

### ISSUE THREAD

**Issue by tomdale** [typed-ember/ember-cli-typescript#891]
At least the "In apps" and "In addons" links in the README TOC no longer point to sections that still exist, and don't do anything when clicked.

**Comment by ro0gr** [comment]
Thanks for catching! These links have lost their power recently, after we've got rid of installation differences between apps and addons.

**Comment by ro0gr** [comment]
see #623

**Comment by chriskrycho** [comment]
Oh! Thanks much, @tomdale! @ro0gr looks like you have a branch for this – I will happily merge a PR!

**Comment by ro0gr** [comment]
@chriskrycho sure, here it is https://github.com/typed-ember/ember-cli-typescript/pull/893
