### ISSUE TITLE
Missing overloads for some computed property macros

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#896]
### Which package(s) does this problem pertain to?
  - [x] @types/ember__object

Ember, I think since 3.9 or something, accepts an intermediate argument for the computed property macros `sort`, `filter`, etc, which is an array of dependencies. Used like so:

```javascript
  foo: sort('bar', ['bar.@each.baz'], function(bar1, bar2) {
    return ...
  })
```

But translating this to use decorators:

```javascript
  @sort('bar', ['bar.@each.baz'], function(bar1, bar2) {
    return ...
  })
  foo;
```

Causes `Expected 2 arguments, but got 3.`. This is the type definition:

```typescript
export function sort(
    itemsKey: string,
    sortDefinition: string | ((itemA: any, itemB: any) => number)
): ComputedProperty<any[]>;
```

**Comment by chriskrycho** [comment]
Interesting! Can you link to the docs with it? That'd be super helpful!

**Comment by boris-petrov** [comment]
@chriskrycho - do you mean [this](https://api.emberjs.com/ember/3.13/functions/@ember%2Fobject%2Fcomputed/sort)? Check out the `additionalDependentKeys` part.

**Comment by chriskrycho** [comment]
Thanks for the link! If you open a PR to DefinitelyTyped, we'll definitely get them merged. Otherwise, one of us will try to hit it Soon™.

**Comment by boris-petrov** [comment]
@chriskrycho - I'll probably leave that to you, thanks. :smiley: There is no hurry. :)

**Comment by boris-petrov** [comment]
I believe this issue is no longer relevant with the new Ember preview types.
