### ISSUE TITLE
Component Templates Co-location not working with ts components

### ISSUE THREAD

**Issue by fpauser** [typed-ember/ember-cli-typescript#931]
In a freshly generated ember-app (`ember new sample-app -b @ember/octane-app-blueprint --yarn`) with ember-cli-typescript installed co-location is working with standard *.js components, but it stops working when converting & renaming the component class to *.ts - the co-located ts-component is never initialized.

My env:
```
ember -v
ember-cli: 3.14.0-beta.2
node: 12.13.0
os: linux x64

tsc -v
Version 3.6.4

yarn list --pattern 'ember-cli-typescript'
yarn list v1.19.1
warning ../../../package.json: No license field
├─ @ember-data/adapter@3.13.1
│  └─ ember-cli-typescript@2.0.2
├─ @ember-data/model@3.13.1
│  └─ ember-cli-typescript@2.0.2
├─ @ember-data/serializer@3.13.1
│  └─ ember-cli-typescript@2.0.2
├─ @ember-data/store@3.13.1
│  └─ ember-cli-typescript@2.0.2
├─ @glimmer/component@0.14.0-alpha.13
│  └─ ember-cli-typescript@2.0.2
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@3.0.0
├─ ember-data@3.13.1
│  └─ ember-cli-typescript@2.0.2
└─ ember-load-initializers@2.1.1
   └─ ember-cli-typescript@2.0.2
```

**Comment by dfreeman** [comment]
@fpauser What version of `ember-cli-htmlbars` are you using? As we worked out in https://github.com/typed-ember/ember-cli-typescript/issues/820, that's the operative package for template colocation, but as far as I knew the TS-specific issues were sorted out.

**Comment by fpauser** [comment]
My bad, everything is fine - closing this bug...
