### ISSUE TITLE
setComponentManager export issue in Octane addon

### ISSUE THREAD

**Issue by mydea** [typed-ember/ember-cli-typescript#951]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [X] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?

* Checkout https://github.com/mydea/ember-addon-output/tree/octane-ts
* Run `yarn tsc`

You'll get the following error:

```
node_modules/@glimmer/component/addon/index.ts:2:10 - error TS2614: Module '"@ember/component"' has no exported member 'setComponentManager'. Did you mean to use 'import setComponentManager from "@ember/component"' instead?

2 import { setComponentManager } from '@ember/component';
```

##### Reproduction Case
It works if I change the file `addon/components/glimmer-component.js` to import from `@ember/component` instead of `@glimmer/component`.

Note that the same does seem to work in an app (instead of an addon) - I tried in `ember-new-output` and that seemed OK.

**Comment by chriskrycho** [comment]
Thanks for reporting this! We spent some time poking at it today and will *hopefully* be able to work out a fix for it soon! Getting stuff ship-shape for Octane is a high priority for us!

**Comment by chriskrycho** [comment]
Fixed by shipping types from Ember natively!
