### ISSUE TITLE
Tests are not generated in Octane enabled project

### ISSUE THREAD

**Issue by btecu** [typed-ember/ember-cli-typescript#966]
Using `ember-cli`: `3.14`, `ember.js`: `3.14` with Octane enabled and latest version of `ember-cli-typescript` as of now (`3.1.1`).

When generating a component, no test files get created.
Trying to generate a test file via `ember g component-test someComponent` will cause `ember-cli` to install `ember-cli-htmlbars-inline-precompile@^0.3.1` and then fail because it requires `ember-cli-babel` version `5`.

cc @chriskrycho

**Comment by chriskrycho** [comment]
This stops being a problem by removing `ember-cli-typescript-blueprints`.

**Comment by chriskrycho** [comment]
Given the state our blueprints are in—very out of date, and *mostly* unnecessary in an Octane world (we really just need a "change the extension" transform for everything except components and *maaaaybe* tests, and those need only simple extensions)—I propose we stop installing them by default for now. cc. @jamescdavis @dfreeman @mike-north

**Comment by chriskrycho** [comment]
Resolved by Ember shipping its own TS blueprints, including for tests. 🎉
