### ISSUE TITLE
Addons using typescript 3.7 features will fail in some consuming apps and addons

### ISSUE THREAD

**Issue by runspired** [typed-ember/ember-cli-typescript#994]
This appears to be an issue with how yarn does/does-not hoist/un-hoist dependencies when a lockfile is present and a new version of a dependency or dev-dependency is being installed.

In our case, we locally create a tarball for our packages and install them into the latest master of various projects to test compatibility  (so that our test is as close to a real install as possible).

Our test setup has this dependency tree of the most important bits, and is using yarn.

```
ember-observer/client (@master) (has lockfile)
  devDep on ember-data (@master)
     dep on ember-cli-babel (@ ^7.13.0)
     dep on ember-cli-typescript (@ ^3.1.1)
```

What we find is that if we don't regenerate ember-observer's lockfile, we fail to build due to typescript parsing issues with `asserts` (and possibly nullish coalescing, but definitely with asserts).

If we force lockfile regeneration during our test process then the test is successful.

**Comment by chriskrycho** [comment]
Thank you for opening this!

The failure mode here seems to be error messages where Babel doesn't understand the syntax – e.g. `asserts someValue is SomeType`. You'll see this fail with something like `Unexpected token, expected "{"`, because the version of Babylon (Babel's parser) that's actually being run is *not* one that includes the relevant TS syntax.

**Comment by chriskrycho** [comment]
Possible workarounds:

- regenerate your `yarn.lock` or `package-lock.json` (this may or may not do it, depending on what your dependency graph looks like, and it may or may not be viable)
- use Yarn's `resolutions` to require that you resolve an exact version of Babylon which supports the syntax

**Comment by chriskrycho** [comment]
Closing this as we haven't seen further reports of it (since Babel got support for this feature out long since), and I *believe* that this issue just existing is enough to help people resolve it if they *do* hit it.
